### ISSUE TITLE
Filter when having several somfy sites is not filtering

### ISSUE THREAD

**Issue by omarquet** [Minims/SomfyProtect2MQTT#10]
I have 2 somfy sites, i try to filter only one in home assistant, standard config is:
  sites:
    - Maison
  
But i still see in MQTT and HomeAssistant the other site's devices. 
For now as a workaround, i created a new somfy account which can only see 1 site, and used this account in SomfyProtectMQTT.

**Comment by Minims** [comment]
Can you confirm the sites have different names / label ?

**Comment by Minims** [comment]
Have you this line 2 times , 1 per site in your logs ?

`Storing Site ID for {site.label}`

**Comment by Minims** [comment]
So the code don't push HA Discovery topic for unwanted site, but was updating the status of this site. 
I have just fixed this part in dev branch. 

Delete the old topics, and retry. If you have setup both site at the beginning remove also de HA config topic for this site.

**Comment by omarquet** [comment]
Got only 1 : Storing Site ID for {site.label}
I'll give a try to the latest dev branch. 
My main problem was that i had the whole bunch of devices added from the other Site, not just the site.

**Comment by Minims** [comment]
I have merge my fix in master. Tell me if it fix your issue.
