### ISSUE TITLE
CPU usage of 25% after updating to 2023.8.0

### ISSUE THREAD

**Issue by bramhoosemans** [Minims/SomfyProtect2MQTT#105]
Hi, after updating to 2023.8.0 the add-on uses 25% of the CPU of my rpi4.. Restart will fix the issue temporarily, but after some time I notice the CPU usage (and temperature) rise again.

**Comment by macje1968** [comment]
Same behavior over here. High cpu usage

**Comment by Minims** [comment]
Try 2023.8.1, it seems to be better

**Comment by macje1968** [comment]
> Try 2023.8.1, it seems to be better

(Y)
