### ISSUE TITLE
Keep snapshots history

### ISSUE THREAD

**Issue by Meow-ops** [Minims/SomfyProtect2MQTT#108]
Is there a way to have all snapshots saved instead of having only the last one?

**Comment by Minims** [comment]
Hello, 
Where do you want to save those snapshot, 1 snapshot every 10s will need a big storage.

**Comment by Meow-ops** [comment]
indeed, I will have to add a file rotation to delete older files when the directory becomes too big

**Comment by Minims** [comment]
Are you using it as an HA Addons, or are you running it on a linux host ?
If i add a config option to write snapshot into a file called snapshot-<timestamp>.jpg  is Ok ?
But It won't be a good idea to use this on HA addons

**Comment by Meow-ops** [comment]
I use it on HA Addons, in its current state I have a third party script that copies the last snapshot from the mounted docker folder into another folder.
The best I could have is multiple options but writing into a file is ok for me!

**Comment by Minims** [comment]
What solution would you prefer to use for this feature ? 
scp  to another hosts for example ?

**Comment by Meow-ops** [comment]
Using HA, there is the "Medias" tab, snapshots could be locally saved here or sent through Mosquitto?
The main "My media" folder can be configured locally on HA or using a network mounted filesystem which is nice for external storage if needed..
But I am not familiar enough with HA system, there are maybe better solutions

**Comment by Minims** [comment]
Is this is not a better solution ?  https://community.home-assistant.io/t/save-a-camera-snapshot-with-archive-when-motion-is-detected/256606/1

**Comment by Meow-ops** [comment]
absolutely! Let me try this

**Comment by Meow-ops** [comment]
Hi,
Sorry to reopen this issue, I just have a problem using the blueprint with this integration in the motion_detector part.
I tried creating the motion_detection service as follows in configuration.yml:
```
binary_sensor:
    - name: ffmpeg_motion
    platform: ffmpeg_motion
    input: main.camera_snapshot # I don't think this work
```

Would you know how I can use the mqtt camera snapshots in the ffmpeg_motion module?

**Comment by Minims** [comment]
Hello, 
You havé to update the blueprint and remove the input Motion part.
There is no motion détection here.
Just save the snapshot évery x seconds
