### ISSUE TITLE
Alerte de "mise en garde"

### ISSUE THREAD

**Issue by romainalca** [Minims/SomfyProtect2MQTT#109]
Bonjour,

Serait-il possible d'ajouter la possibilité de lancer manuellement le son de "mise en garde" de l'alarme intérieure ?
Je souhaite simuler le même comportement que celui des détection de présence ou d'ouverture lorsque l'alarme est activée mais pour des sondes en dehors de Somfy.
Pour l'instant, j'ai pu utilise somfyProtect2Mqtt dans Openhab (simplement en sniffant le contenu de mon Mqtt avec les commandTopic proposés). Il ne me manque que cette fonctionnalité pour avoir un système totalement fonctionnel.

Merci d'avance.
![Screenshot_2023-08-02-17-21-26-565_com myfox android mss](https://github.com/Minims/SomfyProtect2MQTT/assets/24453248/15d43c58-5a02-49cd-98e8-a3ea389d08d4)

**Comment by Minims** [comment]
Hello, 

Comment j'accede a ce menu dans l'app, je ne le connais pas.

**Comment by romainalca** [comment]
Dans la vue "Mes équipements", en sélectionnant la sirène intérieure et en sélectionnant "Tester la sirène" on obtient la liste des différents sons qu'on peut tester :
![IMG_20230803_092217](https://github.com/Minims/SomfyProtect2MQTT/assets/24453248/7457490e-fd5d-4392-a588-6e3868e1cd4e)
![IMG_20230803_092438](https://github.com/Minims/SomfyProtect2MQTT/assets/24453248/80e826d6-8f13-463b-ad5f-9f6946b65526)
![IMG_20230803_092227](https://github.com/Minims/SomfyProtect2MQTT/assets/24453248/62355f15-e1ee-4838-ae47-bad97fe4f840)

**Comment by Minims** [comment]
J'ai ajouté des boutons qui, je pense font ce que tu veux, je n'ai pas pu tester.
C'est en place sur la version de dev si tu veux essayer.

**Comment by romainalca** [comment]
Il faudrait que j'installe une version parallèle de dev pour avoir un deuxième topic dédié et ne pas impacter mes utilisations existantes des commandes.
Dans le fichier de conf je peux choisir le nom du topic général ?
L'idée serait de faire un somfyprotect2mqttdev.
Merci.

**Comment by Minims** [comment]
Oui tu as : 
```
  topic_prefix: "somfyProtect2mqtt"
  ha_discover_prefix: "homeassistant"
```

**Comment by Minims** [comment]
https://github.com/Minims/SomfyProtect2MQTT/releases/tag/2023.8.2 released. This included the button to test.

**Comment by Minims** [comment]
Fixed in 2023.9.1
