### ISSUE TITLE
HA 2023.8.0: MQTT entity naming has changed

### ISSUE THREAD

**Issue by ScratMan** [Minims/SomfyProtect2MQTT#110]
There is a breaking change in HA 2023.8 to the way MQTT devices and entities are named. This makes SP2MQTT entities trigger a "repair" alert in HA.

![Screenshot_20230802-230523](https://github.com/Minims/SomfyProtect2MQTT/assets/971926/f72c44cd-131b-4a47-a919-ad445f7b7859)

The MQTT messages need to be changed. Please have a look here:
https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099
And here:
https://github.com/home-assistant/core/pull/95159

**Comment by Minims** [comment]
Hello, found that yesterday too, will try to make the update for september.

**Comment by Minims** [comment]
dev version updated. 
It seems working. I f you already have the dev addons, rebuild it from the HA interface to get the update.

WIll be merge soon if no issue reproted on this dev branch.

**Comment by ScratMan** [comment]
> dev version updated. It seems working. I f you already have the dev addons, rebuild it from the HA interface to get the update.
> 
> WIll be merge soon if no issue reproted on this dev branch.

I'm using the docker container, I could help if possible to build a Dev test image.

**Comment by Minims** [comment]
@ScratMan 2023.8.2-dev published on DockerHub

**Comment by ScratMan** [comment]
I switched to the Dev release, and I still see the Somfy apparels in the list of devices with entities names starting with device's name.

![Screenshot_20230807-225335](https://github.com/Minims/SomfyProtect2MQTT/assets/971926/05da8648-de8f-473c-8cb8-edb6d6fb154f)

**Comment by Minims** [comment]
Have you restart HA too ?

**Comment by ScratMan** [comment]
Yes

**Comment by Minims** [comment]
Quite strange, i cannot reproduce, it might be the docker version. i have repush the version.

**Comment by ScratMan** [comment]
I downloaded again the image and restarted the container, ignored the alerts in HA and restarted it, and only the alert for ZigBee2MQTT came back.
So it works, but alert seems to be persistent when restarting HA, so it requires to clear it first.

**Comment by Minims** [comment]
https://github.com/Minims/SomfyProtect2MQTT/releases/tag/2023.8.2 released
