### ISSUE TITLE
Add watermak to snapshots

### ISSUE THREAD

**Issue by otorikateo** [Minims/SomfyProtect2MQTT#111]
Hello, would it be possible to add a watermark with date and time on camera snapshots?
Thanks

**Comment by Minims** [comment]
Hello, i need to check what can be done in python to do this, but i'll try to add this in a future release.

**Comment by Minims** [comment]
Hello, snapshot available in the dev version.

**Comment by otorikateo** [comment]
Hello, thanks ! I don't have the dev version on my server though. But looking forward to see it on a further release!

**Comment by Minims** [comment]
2023.8.3 released. is OK on HA addon. I have not tested the Dockerfile image pushed on the hub.
