### ISSUE TITLE
Device lost or present

### ISSUE THREAD

**Issue by irgusite** [Minims/SomfyProtect2MQTT#12]
Hi, I'm currently testing your add-on, but was curious why having the devices "presence" as lost binary instead of a present binary? 
The latter would better tie into the HA concept of device presence.

Continue the nice work, I have this alarm since 3 years and the IFTTT integration was not the ideal solution!

**Comment by Minims** [comment]
Hi,

The Somfy Api return the status `device_lost`, so I have not reverse it while pushing data to Mqtt. 
If it's a need I can have a Loog to integrate a config param to do this.

**Comment by kefran95** [comment]
Hello,
I would like to use the device_lost status in a condition. Do you have the configuration? 
Thank you. 
Franck

**Comment by Minims** [comment]
> I would like to use the device_lost status in a condition. Do you have the configuration?

You mean trigger the status in home assistant ?

**Comment by kefran95** [comment]
No, I would like to use the information from device_lost to verify the presence of my badges. And if all my badges are missing, send me a notification.

**Comment by kefran95** [comment]
Sorry, I found my mistake. I managed to test the information...

**Comment by kefran95** [comment]
Hello,
I have a problem with the information reported by certain badges. The information is not good. Example with badge A which is not there, we can see it clearly in the Somfy application and yet it is present in HA. An idea ?

![Somfy](https://user-images.githubusercontent.com/32737533/127528234-d858de9c-be48-4b21-ac99-b153dd4065b3.PNG)
![HA](https://user-images.githubusercontent.com/32737533/127528242-8865daec-4082-466d-b62d-fa000d27e4a1.PNG)

**Comment by Minims** [comment]
Hello, i have no idea for the moment, I will make some new tests in few weeks on my installation to check if I have the same issue.

**Comment by Minims** [comment]
I can't reproduce for now. What I saw is that the sensor is reset to 'Inactif' on HomeAssistant Upgrade/Restart.
Is this issue is permanent ?

**Comment by kefran95** [comment]
No, it's not permanent, but really random. For 2 days I had no more problems, and this evening I have again a missing badge although it is present in Somfy...

**Comment by kefran95** [comment]
Hi,
I have a question. Do you retrieve the badge information from recent activity or from the home page (icon in blue or gray)?
By looking, in recent activity, it happens that the departure of my badge does not appear. Which could explain the erroneous information, right?

**Comment by Minims** [comment]
Hello, none of them I do no parse the application page, as it can be done on a web page.
 I call the somfy api on site/{site}/device)/{device_id_of_badge}

**Comment by kefran95** [comment]
Is it possible to view the API information? I really have the impression that if the departure of the badge is not in the activities, the information of the badge does not update.

**Comment by Minims** [comment]
> Is it possible to view the API information? I really have the impression that if the departure of the badge is not in the activities, the information of the badge does not update.

You need to use my python  api client directly with your credential and display the api result to check what comfy return : 
https://github.com/Minims/somfy-protect-api

**Comment by Minims** [comment]
Update pushed on dev branch. 
This is an alpha release, not fully tested. 
I have add : 

- immediate device precence notification
- immediate alram status notification, including alarm is ringing
