### ISSUE TITLE
The sound control of the siren doesn't work

### ISSUE THREAD

**Issue by Thyphus** [Minims/SomfyProtect2MQTT#121]
I updated the version of my home assistant SomfyProtect2MQTT from 8.3 to 9.1 (and after from 9.1 to 9.2). I can't disable the sound notification of the siren (indoor and outdoor) in the MQTT device.
I didn't rollback in 8.3 to test if the sound control work again.

**Comment by Minims** [comment]
Hello, issue found . Fixed in dev. 2023.9.3 will be release this evening

**Comment by Minims** [comment]
2023.9.3  released

**Comment by Thyphus** [comment]
It's fixed. Thank you for your reactivity.
