### ISSUE TITLE
Massive CPU increase since update

### ISSUE THREAD

**Issue by zaggash** [Minims/SomfyProtect2MQTT#123]
I see an increase of CPU usage on the addon since the latest 2023.9.3 update.

Usually on the Addon monitoring page, I see almost no usage, near 0.
After the update,  it stays close to 50%.

I restored the Home Assistant backup before the upgrade and it came back to normal.

For now, I'll stay on 2023.9.2 !

**Comment by newkindofworld** [comment]
Exactly the same problem here, CPU usage stuck at 50% with 2023.9.3 version.
Reverting to 2023.9.2 fixes the CPU usage.

**Comment by Minims** [comment]
Must be fixed in 2023.9.4
