### ISSUE TITLE
Can't change alarm state

### ISSUE THREAD

**Issue by ScratMan** [Minims/SomfyProtect2MQTT#128]
Hello, with latest docker container, I get some errors in the log of HA when the alarm state is changed using Somfy app or key fob, but state in HA is updated correctly. No error appear in container's logs.

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:747
First occurred: 09:09:28 (1 occurrences)
Last logged: 09:09:28

Template variable warning: 'list object' has no attribute 'security_level' when rendering '{{ value_json.security_level }}'
```

```
Logger: homeassistant.components.mqtt.alarm_control_panel
Source: components/mqtt/alarm_control_panel.py:206
Integration: MQTT (documentation, issues)
First occurred: 09:09:28 (1 occurrences)
Last logged: 09:09:28

Received unexpected payload: [{"security_level": "armed_away"}]
```

But when I try to change the alarm state using HA, nothing happens, and there is no error logged either in HA or in container.

Reverted back to 2023.8.2, now HA can change alarm's state, but errors are still present in HA log.

**Comment by Minims** [comment]
It can be the  `mqtt naming' patch. Can you try to delete the alarm device from MQTT, then restart the add-on and check the new alarm device created in HA ?

**Comment by ScratMan** [comment]
I reinstalled the latest version, and error messages and issue did not come back. Weird issue, but closed.
