### ISSUE TITLE
Add code to disarm

### ISSUE THREAD

**Issue by glienart** [Minims/SomfyProtect2MQTT#13]
This is great to replace IFTTT which is slow and unreliable, thank you.
A feature that would great is the possibility to arm/disarm with a code just like the alarm control panel.

**Comment by Minims** [comment]
You mean you already have a code to arm/disarm in the SomfyProtect App ?  
Or you just want to be able to arm/disarm with code only in HA ?

**Comment by Minims** [comment]
@glienart You can test the dev version of my add-on fork : https://github.com/Minims/homeassistant-addons
If it's ok, I will make all the PR to make it available in master
```
...
  sites:
    - Maison
  code: 1234
...
```

**Comment by glienart** [comment]
@Minims I have tested and in LoveLace i Still get without the keypad :
![image](https://user-images.githubusercontent.com/8383279/117569913-312e5580-b0c8-11eb-8e1e-484f5de6a71a.png)
when I call the service, with or without password i am able to arm/disarm the password. If the password is incorrect it also works.
Thank you for the speed!!

**Comment by Minims** [comment]
Can you paste you configuration, indentation might be wrong.
Remove you credentials before paste.

In the log of the add on, do you see the code in the printed configuration when you start the add-on

**Comment by glienart** [comment]
@Minims This actually works great! I had the dev from schumijo installed thinking that it would just fetch your last update, but I was wrong. I installed the add-on manually and now works great. The hint was that the "code" was not printed in the log.
This is a great addition.

**Comment by glienart** [comment]
At least for my use, i don't find it necessary to have to put a code to arm. I would like to be able to set code_arm_required to false.
FYI: I have a touchscreen that is always on in my home and don't mind anybody using it to arm but I don't want somebody to just disarm it, let's say a robber or....

**Comment by Minims** [comment]
Ok, I will merge this in master in the following weeks. 
Maybe I will add some additional thing/fix in the meantime.

**Comment by Minims** [comment]
Merged in master.
PR made in official add-on repo.

**Comment by vxav** [comment]
Just wanted to say thanks for this PR!
[This](https://github.com/Minims/SomfyProtect2MQTT/blob/master/somfyProtect2Mqtt/config/config.yaml.example#L12) is simple yet effective UX 👌
