### ISSUE TITLE
WebRTC Camera

### ISSUE THREAD

**Issue by k2v1n58** [Minims/SomfyProtect2MQTT#130]
Hi,

I try to use the webRTC using the README but I don't know what to set as <camera device_id> here.
```
streams:
  somfy_indoor_camera_echo:
    - echo:/config/echo/somfy.sh <camera device_id>
```

**Comment by Minims** [comment]
Hello,

if you start a stream with cover open via the mqtt switch , you will find a file in /config/somfyprotect2mqtt/stream_url_<device-id> just copy paste this id

**Comment by k2v1n58** [comment]
Do I need to copy paste everything: rtmps://ip-XX-XX-XX-XX.myfox.io/live/livecamera-xxxxxxxx

So my go2rtc.yaml should look like

`streams:
  somfy_indoor_camera_echo:
    - echo:/config/echo/somfy.sh rtmps://ip-XX-XX-XX-XX.myfox.io/live/livecamera-xxxxxxxx`

**Comment by Minims** [comment]
You have taken the file content not the id in the filename:
```
stream_url_LKJHGFGHJKLKGFGYIOPOYG
```

device_id is `LKJHGFGHJKLKGFGYIOPOYG` here

then :
```
streams:
  somfy_indoor_camera_echo:
    - echo:/config/echo/somfy.sh LKJHGFGHJKLKGFGYIOPOYG
    ```

**Comment by k2v1n58** [comment]
I properly set the device_id and I changed the streaming from mqtt to go2rtc on the add-on somfyprotect2mqtt but go2rtc shows me the following error message

`11:32:12.184 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: exec: exit status 1"`

I'm not sure somfy.sh comminucates with the add-on somfyprotect2mqtt

**Comment by Minims** [comment]
Can you paste your go2rtc full config ?
To make the stream work, you have to open cover and start the stream from the entity switch stream.

The stream work for about 2min then you need to request a new start stream. 

You might need to reload your ha page one stream has start

**Comment by k2v1n58** [comment]
It now works

Thanks

**Comment by ChristopheP59** [comment]
Hello,

I can't access to the stream, I have this error : 
mse: streams: fork/exec /config/echo/somfy;sh: permission denied

Do you have a solution ? Thx

**Comment by Minims** [comment]
Hello,

Why is your file seems named `/config/echo/somfy;sh` instead of `/config/echo/somfy.sh`

```
root:~# ls /config/echo/somfy.sh -la
-rwxr-xr-x    1 root     root           119 Nov 15 22:11 /config/echo/somfy.sh
root:~#
```

Try : 

```
chmod +x /config/echo/somfy.sh
```
