### ISSUE TITLE
Compatibility ArmV7

### ISSUE THREAD

**Issue by anthopocket** [Minims/SomfyProtect2MQTT#132]
hi,

i have installed this repo witch docker on RPI 3B ARMV7. But this addon is not compatible.

![image](https://github.com/Minims/SomfyProtect2MQTT/assets/62506538/24d16148-9172-4731-b072-0b0bbbb12b77)
Is it possible to make it compatible?
Thanks

**Comment by Minims** [comment]
Hello,

i have removed the armv7 because it does not build anymore. Will try again.

**Comment by anthopocket** [comment]
thanks you for you return
