### ISSUE TITLE
Intégration de Alarme SOMFY

### ISSUE THREAD

**Issue by axgdcode** [Minims/SomfyProtect2MQTT#137]
Bonjour,

Est-il planifié de faire une intégration des alarmes qui sont commandées via ALARME SOMFY ?
Un plugin Jeedom existe : https://github.com/fdp1nm/plugin-protexiom.
Je suis partant pour aider à faire des tests. 

Merci par avance pour votre aide.

_Références des applications_
- https://market.jeedom.com/index.php?v=d&p=market_display&id=510 
- https://play.google.com/store/apps/details?id=fr.somfy.homemotion

**Comment by Minims** [comment]
Hello,

Ce n'est pas prévu et je ne vois pas d'api dsponible pour cette alarm.

Il y a ce projet, il ne fonctionne pas. ?  https://github.com/Pschittt/HASS-Somfy-Protexiom
