### ISSUE TITLE
Entité ne se met pas à jour

### ISSUE THREAD

**Issue by cersyl** [Minims/SomfyProtect2MQTT#138]
Bonjour,
Depuis quelques jours j'ai un soucis avec SomfyProtect2MQTT.
Jusqu'à maintenant j'avais la version DEV et même en stable j'ai toujours le soucis.
Au démarrage ou redémarrage de l'addon, je change le statut de l'alarme avec le badge ou l'application somfy, le statut de l'alarme se met bien à jour ; par contre au bout d'un moment, lorsque je je modifie l'état de l'alarme, je vois bien dans les logs que le statut de l'alarme se met bien à jour, par contre mon entité ne se mets plus à jour, ce qui fait que mes automatisations basées sur le statut de l'alarme ne fonctionnent plus. Je redémarre l'addon et ca refonctionne un moment...

J'utilise depuis pratiquement un an cet addon et je n'ai jamais eu le soucis....

**Comment by Minims** [comment]
Hello,

Tu n'as pas mis a jour ton server MQTT ? 
Est ce que si tu as active le debug tu vois des soucis sur la communication MQTT ?

**Comment by cersyl** [comment]
Merci de ta réponse rapide.
Alors la seule modif c'est que j'ai changé de nom de domaine de duckdns a freeboxos, j'ai modifié dans tous les addons et j'avais oublié dans le config.yaml.... hier j'ai supprimé l'alarme, désinstaller ton Addon, réinstallé et pour l'instant ça a l'air de fonctionner correctement.. je teste quelques jours et je te fais un retour.
Encore merci pour ton travail et pour ton implication.

**Comment by cersyl** [comment]
Bon, pas mieux, à quel niveau je dois mettre l'IP au lieu du ndd ??
Merci

**Comment by Minims** [comment]
Dans la config de l’addon pour mqtt

# MQTT Configuration
mqtt:
  host: 192.168.1.10

**Comment by cersyl** [comment]
Re,
J'avais déjà l'adresse locale dans l'addon... J'ai fait machine arrière, je suis revenu sous duckdns, tout refonctionne, par contre toujours le même problème pour la mise à jour du status de l'alarme, ça fonctionne pendant un moment puis ensuite àa ne se met plus à jour... je vais activé le debug et voir ce qui se passe...

**Comment by Minims** [comment]
Est ce que tu as les logs de juste avant ?

**Comment by cersyl** [comment]
Voilà le genre de logs que je retrouve avant le ERROR websocket...

2023-12-05 03:05:01,017 [INFO] [somfy_protect.websocket:403] [default] Read Message {'profiles': ['owner', 'admin'], 'site_id': 'yYpcjOjZzFNg1qbznnSrvQCioaLnpZ7V', 'type': 'testing', 'key': 'site.device.testing.status', 'diagnosis': {'main_status': 'device-warning', 'main_message': 'dashboard.diagnosis.device.warning', 'main_message_vars': {}, 'device_diagnosis_available': True, 'device_diagnosis_expired': False, 'items': [{'device_id': 'p26ocrimij4IXRl55nEH7FwWRY7cDzHT', 'problem': 'low_battery'}]}, 'message_id': 'yYpcjOjZzFNg1qbznnSrvQCioaLnpZ7V656e854cf1582'} 2023-12-05 03:05:01,612 [INFO] [somfy_protect.websocket:403] [default] Read Message {'profiles': ['admin', 'owner', 'installer_write'], 'site_id': 'yYpcjOjZzFNg1qbznnSrvQCioaLnpZ7V', 'type': 'testing', 'key': 'device.status', 'device_id': 'ngJmQwHho30I0GtVZrJLlPKpGfdjtH9r', 'device_lost': False, 'wifi_level': -21, 'wifi_level_percent': 99, 'power_mode': 'current', 'last_status_at': '2023-12-05T02:05:01.000000Z', 'diagnosis': {'is_everything_ok': True, 'problems': []}, 'message_id': 'yYpcjOjZzFNg1qbznnSrvQCioaLnpZ7V656e854d8e804'} 2023-12-05 03:05:01,613 [INFO] [somfy_protect.websocket:368] It Seems the Door ngJmQwHho30I0GtVZrJLlPKpGfdjtH9r is moving

**Comment by Minims** [comment]
Honnêtement je ne sais pas trop pourquoi. J’ai fais quelques changements sur la version dev concernant le websocket. Il faudrait voir si c’est mieux

**Comment by Minims** [comment]
J’ai fais la correction en fin de soirée c’est bien la 2023.12.0 qui tourne quand tu redémarres l’addon ?

**Comment by cersyl** [comment]
Non, 2023.11.1

**Comment by Minims** [comment]
Fait reconstruire sur l’addon

**Comment by cersyl** [comment]
C'est bon, 23.12.0.

**Comment by cersyl** [comment]
Depuis les modifications, cela semble se déconnecter moins souvent, mais je relance l'addon au minimum 2 fois par jour.
J'ai créé une automatisation qui relance l'addon toutes les 2 heures pour pallier au problème...

**Comment by Minims** [comment]
Ici tout va bien je ne vois pas de reconnexion. On est d'accord que l'on parle uniquement de la partie connexion websocket pour la reception de message somfy ?

**Comment by cersyl** [comment]
Quand j'agis sur l'application ou le badge Somfy et que l'entité se met bien à jour, c'est ce genre de logs "normaux" :

2023-12-15 21:55:08,129 [INFO] [business:314] Update Devices Status 2023-12-15 21:55:08,504 [INFO] [business:290] Update Sites Status 2023-12-15 21:55:08,753 [INFO] [business:294] Update Maison Status

Vu que je redémarre l'addon avec une automatisation, j'ai pas de logs récents, je vais arrêter mon automatisation pour voir si cela se reproduit.... Une chose m'interpelle, les logs parlent de python 3.11, or quand je parcours les fichiers je n'ai pas de dossier python 3.11 mais 3.10.....

**Comment by Minims** [comment]
Je vais redémarrer la connection WebSocket toutes les heures pour voir et peut être le coupler à l'historique

**Comment by Minims** [comment]
2023.12.0 a tester

**Comment by cersyl** [comment]
En test depuis quelques jours, ça semble tenir... Merci pour tout.

**Comment by Grui** [comment]
Hello similar issue here

despite this log

2024-01-03 21:28:04,552 [INFO] [somfy_protect.websocket:444] [default] Read Message {'profiles': ['owner', 'admin', 'guest', 'kid'], 'site_id': 'xxxx', 'type': 'config', 'key': 'security.level.change', 'security_level': 'disarmed', 'message_id': 'Oz2ff39iztTVL9pk9je2Fr1m8dsFWhYU6595c3547e940'}
2024-01-03 21:28:04,553 [INFO] [somfy_protect.websocket:256] Update Alarm Status
2024-01-03 21:28:09,062 [INFO] [business:381] Update Devices Status
2024-01-03 21:28:12,603 [INFO] [somfy_protect.websocket:444] [default] Read Message {'profiles': ['owner', 'admin', 'guest', 'kid'], 'site_id': 'xxxx', 'type': 'config', 'key': 'security.level.change', 'security_level': 'partial', 'message_id': 'Oz2ff39iztTVL9pk9je2Fr1m8dsFWhYU6595c35c8add0'}

The alarm control panel is stucked to disarmed.
Was working fine several weeks ago.

version 2023.12.2

**Comment by hutch1313** [comment]
Bonjour, j'ai le même problème depuis le mois de décembre avec l'envoie des message et la mise à jour de statut qui ne se fait plus après quelques heures de fonctionnement. Après un redémarrage de l'addon cela refonctionne de nouveau quelques heures. 
Quelques fois mon déclencheur sur l'event de désactivation se lance avec un retard de 10 minutes

![image](https://github.com/Minims/SomfyProtect2MQTT/assets/152629705/5c55f70b-f99c-4976-a1f9-5ce5ee504270)

![image](https://github.com/Minims/SomfyProtect2MQTT/assets/152629705/28fcd5a4-ab6b-4e2d-bcd6-a576c815dfdb)

**Comment by Minims** [comment]
> Hello similar issue here
> 
> despite this log
> 
> 2024-01-03 21:28:04,552 [INFO] [somfy_protect.websocket:444] [default] Read Message {'profiles': ['owner', 'admin', 'guest', 'kid'], 'site_id': 'xxxx', 'type': 'config', 'key': 'security.level.change', 'security_level': 'disarmed', 'message_id': 'Oz2ff39iztTVL9pk9je2Fr1m8dsFWhYU6595c3547e940'} 2024-01-03 21:28:04,553 [INFO] [somfy_protect.websocket:256] Update Alarm Status 2024-01-03 21:28:09,062 [INFO] [business:381] Update Devices Status 2024-01-03 21:28:12,603 [INFO] [somfy_protect.websocket:444] [default] Read Message {'profiles': ['owner', 'admin', 'guest', 'kid'], 'site_id': 'xxxx', 'type': 'config', 'key': 'security.level.change', 'security_level': 'partial', 'message_id': 'Oz2ff39iztTVL9pk9je2Fr1m8dsFWhYU6595c35c8add0'}
> 
> The alarm control panel is stucked to disarmed. Was working fine several weeks ago.
> 
> version 2023.12.2

I don't see any error in this logs.
You stay it's stuck in HA Panel. But what is the real device status in HA.
Are you sure the entity ID has not change ?

**Comment by Minims** [comment]
> Bonjour, j'ai le même problème depuis le mois de décembre avec l'envoi des messages et la mise à jour de statut qui ne se font plus après quelques heures de fonctionnement. Après un redémarrage de l'addon cela refonctionne de nouveau quelques heures. Quelques fois mon déclencheur sur l'event de désactivation se lance avec un retard de 10 minutes
> 
> ![image](https://private-user-images.githubusercontent.com/152629705/297007390-5c55f70b-f99c-4976-a1f9-5ce5ee504270.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjA1MTUsIm5iZiI6MTcwNTc2MDIxNSwicGF0aCI6Ii8xNTI2Mjk3MDUvMjk3MDA3MzkwLTVjNTVmNzBiLWY5OWMtNDk3Ni1hMWY5LTVjZTVlZTUwNDI3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNDE2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTI2MWFlZWQwNGY1NWI2NTE0OTk1MmExZTllZmRhYzJkYjMyNzM1ZWMzYWI2N2NiNDA5Yjc3YzAyMzI1ZGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MLYgT6ku_iSAg4XzC_nMoPNDKQB7_TvwqCplKoYbaJA)
> 
> ![image](https://private-user-images.githubusercontent.com/152629705/297008703-28fcd5a4-ab6b-4e2d-bcd6-a576c815dfdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjA1MTUsIm5iZiI6MTcwNTc2MDIxNSwicGF0aCI6Ii8xNTI2Mjk3MDUvMjk3MDA4NzAzLTI4ZmNkNWE0LWFiNmItNGUyZC1iY2Q2LWE1NzZjODE1ZGZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxNDE2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGNkYzMxZTg3MGY0ZGUyODI1ZjUzOGYxODRkMTAzNzkzODU5NWVhYzk3OGQ5MjU1NTcxYjIzMjczZjMyZmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uYvbcSZyPwNA_a4HnBl8lfakWdXObR3QgJSgcVfCSzs)

Est ce que ca continue de se mettre à jour dans les 60s mais plus instantanément ? 
La mise à jour instantanée se base sur websocket et ceci n'est pas 100% fiable.

**Comment by hutch1313** [comment]
Je fais les tests en attendant 60secondes la semaine prochaine 
Merci pour les reponses !!

**Comment by Minims** [comment]
Avant l'alarme pouvait se mettre à jour toutes les 10s, mais j'ai revu cette valeur a 60s pour éviter trop de requêtes vers l'api Somfy car le nombre d'utilisateur de l'addon augmente et je ne veux pas qu'un blocage sur l'API se produise. Ceci mettrai fin à l'addon.

**Comment by hutch1313** [comment]
Ok je comprend, on était habitué à avoir le retour sous 10 secondes d’où les bugs je pense 
Je verrai au prochain problème
Merci

**Comment by hutch1313** [comment]
Après une semaine de tests, ce ne sont pas les 60 secondes le problème, au bout d'un moment les déclencheurs lorsqu'on active ou désactive l'alarme ne fonctionne plus, obligé de redémarrer tout HA et là ca refonctionne pendant 1 ou 2 journée max.
Même en redémarrant que le plugin cela ne fonctionne pas, faut vraiment tout redémarrer.

**Comment by hutch1313** [comment]
Bonjour, je pense que tu as raison que tout est ok, je me suis rendu compte que quand ca ne fonctionnait plus, soit ton plugin soit le mosquittoBroker avait cessé de fonctionner, donc en cochant l'option "chien de garde" c'est ok je n'ai plus de problème.

Merci beaucoup pour le travail.
