### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by jvanoost** [Minims/SomfyProtect2MQTT#139]
Salut Mimims et merci pour ton travail !

J'utilise depuis plusieurs mois maintenant ton image docker et ça tourne très bien.
Est ce que dans une future version il serait possible d'intégrer dans le fichier de config le niveau de log qu'on souhaite.

Merci d'avance !

**Comment by Minims** [comment]
Hello, j'ajoute ca dans la version dev.

**Comment by Minims** [comment]
Dispo en 2023.12.0

**Comment by jvanoost** [comment]
Top ! Grand merci a toi !
