### ISSUE TITLE
siren temperature does not update

### ISSUE THREAD

**Issue by momomie** [Minims/SomfyProtect2MQTT#141]
hello, first thx for this integration ! 

I have a problem with the temperature from the outdoor siren, it doesn't return informations periodically 

do you have a trick to do that ? thx !

**Comment by Minims** [comment]
Hello, 

it must work out of the box.

The t° is update only if there a "big" change.
For example mine can stay a the same t° for 6 hours. but usually my temp is updated every 30min/40min

**Comment by momomie** [comment]
working fine this night, thx !
