### ISSUE TITLE
Event d'activation de l'alarme avec le clavier sans code KO

### ISSUE THREAD

**Issue by hutch1313** [Minims/SomfyProtect2MQTT#146]
Bonjour,

Après quelques tests sur l'évènement de l'activation de l'alarme par le clavier somfy home, je me rends compte que si j'active l'alarme sans code, l'évènement n'arrive pas dans homeAssistant sinon il arrive bien.
![image](https://github.com/Minims/SomfyProtect2MQTT/assets/152629705/7a594afd-fdc4-4d97-adf7-abda7cf6a5c4)

En vous remerciant pour votre travail !!!

**Comment by Minims** [comment]
Hello,

Est ce que tu peux détailler un peu plus.

Tu actives l'alarme sans code comment ? Sur le clavier, dans l'application , via HA ? 
Car peu importe comment l'alarme est activée, si elle est active dans l'application Somfy, alors l'état doit être à jour sous 60s dans HA.

**Comment by hutch1313** [comment]
Merci pour les précisions, je me doutais que c’était la même chose pour les différentes activations. Aujourd’hui ça a fonctionné, je comprend rien,  
quand je le fais sur l’application c’est toujours instantané. Je ne savais pas qu’il y avait un délai de 60 secondes maximum, comme les volets se ferment à l’activation, j’ai jamais vraiment attendu autant.

**Comment by hutch1313** [comment]
Je ferme le bug et je reteste la semaine prochaine l’attente 
En vous remerciant de vos réponses 
Et merci bcp pour cet addon !!

**Comment by Minims** [comment]
Globalement je récupère l'état de l'alarme et des devices toutes les 60secondes. Si jamais je vois un message sur websocket avant, je met à jour tout de suite. Mais le websocket c'est pas super fiable dans le temps. je dois déjà le réinitialiser toutes les 30min :-/
