### ISSUE TITLE
Changement de status ne marche plus depuis HA

### ISSUE THREAD

**Issue by vxav** [Minims/SomfyProtect2MQTT#149]
Bonjour et tout d'abord un grand merci pour cette superbe intégration ! 👏 

Je viens de me rendre compte aujourd'hui que le status l'alarme Somfy n'est pas mis a jour quand je le change dans HA. Aucune activité dans les logs quand je change le status. J'ai tenté d'attendre 60sec+ car j'ai vu dans une issue récente qu'il y a eu un changement de ce coté pour ne pas bombarder l'API Somfy mais pas mieux.

Par contre si je le change par Somfy (application par exemple) le status remonte bien dans HA.

Je suis en `2024.1`.

**Comment by vxav** [comment]
Bon... Après être passé par quelques versions ca fonctionne en `2024.1.0`. Je soupçonne que le fait d'être passé de `0.2.9` a `2023.6.0` ait aidé. Peut être en lien avec [ce breaking change](https://github.com/Minims/SomfyProtect2MQTT/commit/000d75b3b64806e60509dbce5ccacefc0ec9312b)? 🤷

**Comment by Minims** [comment]
Hello,

Effectivement ca semble bizarre ce comportement, il faut que je teste aussi, mais je n'utilise pas HA pour activer/désactiver l'alarme, donc ca fait longtemps que je n'ai pas regardé cette partie. Mais ca expliquerai effectivement les dernières remontées.

J'ai regarder rapidement un diff entre la 0.2.9 et la version actuelle, pour l'instant je ne vois rien qui pourrait expliquer ce changement de comportement.

**Comment by Minims** [comment]
Bon je viens de tester l’activation depuis HA, c’est ok. J’ai redémarré ha il y 2h je ne sais si ca change quelque chose dans le comportement remonté

**Comment by vxav** [comment]
Oui je n'arrive pas non plus à voir le dénominateur commun. Ce que j'ai observé est que si j'ajoute la section "code" dans ma config en 2024.1.0 et recycle le conteneur alors HA ne peut pas changer l'état de l'alarme. Par contre si je redescend en 0.2.9 (pas essayé d'autres pour le coup) et que je remonte en 2024.1.0 alors ça marche.

Je pense que ce n'est pas la peine de passer du temps sur cela si personne d'autre ne remonte de problèmes à ce sujet.

Merci pour la vérification !

**Comment by Minims** [comment]
Concernant le breaking change. 
Tu as essayé de supprimer le device alarm de MQTT et laisser l'addon le recréer ?  Si oui, ca ne change rien ?

**Comment by vxav** [comment]
Ok je pense avoir identifié le problème.  Je fais tourner HA et s2mqtt dans Kubernetes (K3s mais peu importe). Et au moment de modifier le code de l'alarme, je modifiais le secret qui est mappé dans le pod et je supprimais celui-ci pour qu'il prenne en compte le nouveau contenu du secret `k delete pod <mon pod>`. Après ça le panel alarme ne répondais pas dans HA mais quand je changeais l'image ça marchait.

J'ai ensuite découvert qu'il y a une difference de comportement, et ça fonctionne comme prévu si je fais un rollout du deploiement (un seul replica) au lieu de supprimer le pod `k rollout restart deployment <mon pod>`.

J'ai fait cette opération dans plusieurs apps et environnements mais c'est la premiere fois que j'observe ce comportement. Je suis curieux d'en savoir plus mais je ne trouve pas de bonne doc expliquant la vraie diff entre un delete et un restart.
