### ISSUE TITLE
Démarrage auto du container 

### ISSUE THREAD

**Issue by anthopocket** [Minims/SomfyProtect2MQTT#154]
Bonjour,

quand je redémare le container de proxmox ou si mon proxmox redémarre suite à coupure de courant, le container (somfyprotect2MQTT) ne redémarre pas automatiquement.
y a t-il une façon de le faire?

![image](https://github.com/Minims/SomfyProtect2MQTT/assets/62506538/90f4a0eb-c3ce-45c1-9ec4-00bb499c2624)

merci

**Comment by Minims** [comment]
Bonjour,

Je ne sais pas du tout, je ne suis pas un expert sur Docker et ne l'utilise pas. Peut être d'autres personnes ont la réponse, il y a plusieurs sujet dans les issues ces derniers jours autour de l'utilisation du Dockerfile.

Sinon peut etre le forum hacs peut aider sur ce genre de sujet.

**Comment by anthopocket** [comment]
ok je vais chercher.
je pense que j'ai un autre probléme mais je confirmerais demain.
j'ai l'impression qu'au bout de 24h le container ne recoie plus d'info ni de mon serveur mqtt (jeedom) ni depuis somfy

**Comment by Minims** [comment]
Essaye peut etre ceci : 
https://github.com/Minims/SomfyProtect2MQTT/issues/133#issuecomment-1958463369
