### ISSUE TITLE
go2rtc erreur lecture flux rtpms

### ISSUE THREAD

**Issue by turmeauf** [Minims/SomfyProtect2MQTT#155]
Hello,

The stream is indeed present in the somfyprotect2mqtt file, /homeassistant/somfyprotect2mqtt/stream_url_s77RJE76NVQiTUKcTTFPxApaSxsb0fzz: rtmps://ip-10-21-3-247.myfox.io/live/livecamera-xxxtokenIdxxx

When I try to launch it from go2rtc I get this message: undefined error=streams: fork/exec /config/echo/somfy.sh: no such file or directory caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166

My go2rtc config file: 
camera_entree_echo: 
- echo:/config/echo/somfy.sh s77RJE76NVQiTUKcTTFPxApaSxsb0fzz

Thank you in advance for your help.

**Comment by turmeauf** [comment]
thanks for answer.
The response is ‘no such file or directory.’ Here is my file directory structure :
/homeassistant/echo/somfy.sh
i need to create config folder between homeassistant and echo ?

**Comment by Minims** [comment]
Ok so try to create `/homeassistant/echo/` folder. copy/paste `somfy.sh` from the repo in this directory.
Then you might need to update got2rtc to:
```
    - echo:/homeassistant/echo/somfy.sh <camera device_id>

```

**Comment by Minims** [comment]
the camera id from somfy is fixed. It can change if you pair it again with somfy app.

```
root:~# ls config/echo/somfy.sh -la
-rwxr-xr-x    1 root     root           119 Nov 15 22:11 config/echo/somfy.sh

root:~# grep somfy.sh config/go2rtc.yaml
    - echo:/config/echo/somfy.sh <id>
```

the id to use is the same a the one in this file

```
config/somfyprotect2mqtt/stream_url_<id>
```

**Comment by turmeauf** [comment]
**<**camera device_id**>**  do i need these symbols on each side ?

**Comment by Minims** [comment]
No, just put the id without <> just paste the strind id like `SDFGHJ34561ZDFGH`

**Comment by turmeauf** [comment]
I don't kow how it works. I simply delete somfy.sh and reload it.
Thanks for all...
and great work. Thank you.
