### ISSUE TITLE
Add device_class: safety for intellitag

### ISSUE THREAD

**Issue by PoVPoV29** [Minims/SomfyProtect2MQTT#156]
Hello,
Is it possible to add the device_class: safety to intellitag device in the MQTT entities ?
It will add the possibility to use them in "Alarmo".
Thanks.
Regards

**Comment by Minims** [comment]
Hello,

On all entities, or just on motion_sensor ? 

I i set `device_class: motion` for PIR, the intellitag motion_sensor will be the same.

**Comment by PoVPoV29** [comment]
Hello,
The best will be device_class: motion for Myfox Security Infrared Sensor
and 
device_class: safety IntelliTag
If you can only put one device_class for these two type of device, we can try first with safety, I think.
Thanks.

**Comment by Minims** [comment]
device_class updated to safety for Intellitag
Install the dev add-on in HA to test, or rebuild it if already installed.

**Comment by PoVPoV29** [comment]
I tested and it's perfect thanks. Can you mode that to the master branch?

**Comment by Minims** [comment]
https://github.com/Minims/SomfyProtect2MQTT/releases/tag/2024.3.0
