### ISSUE TITLE
add device_class: motion for motion sensor

### ISSUE THREAD

**Issue by PoVPoV29** [Minims/SomfyProtect2MQTT#157]
Hello,
Is it possible to add device_class: motion for the "Myfox Security Infrared Sensor" ?
Thanks
Regards

**Comment by Minims** [comment]
Hello,

Can be tested on dev branch

**Comment by PoVPoV29** [comment]
How Can I test the dev branch ?

**Comment by Minims** [comment]
device_class updated to motion for PIR
Install the dev add-on in HA to test, or rebuild it if already installed.

**Comment by PoVPoV29** [comment]
I test and it's perfect! Thanks!

**Comment by Minims** [comment]
https://github.com/Minims/SomfyProtect2MQTT/releases/tag/2024.3.0
