### ISSUE TITLE
'401 Client Error: Unauthorized for url' Issue after some weeks of usage

### ISSUE THREAD

**Issue by Grui** [Minims/SomfyProtect2MQTT#160]
Hi,

I got an issue after some weeks of usage without any problem and restart.

Impossible to get the Somfy Alarm Status.

Here the log when the issue occurs:

> 2024-04-19 19:54:51,428 [INFO] [business.mqtt:66] Payload partial
> 2024-04-19 19:54:51,429 [INFO] [business.mqtt:87] Security Level update ! Setting to partial
> 2024-04-19 19:54:51,632 [ERROR] [business.mqtt:209] Error when processing message: 401 Client Error: Unauthorized for url: https://api.myfox.io/v3/site/Oz2ff39iztTVL9pk9je2Fr1m8dsFWhYU/security: somfyProtect2mqtt/Oz2ff39iztTVL9pk9je2Fr1m8dsFWhYU/command => b'partial'
> 2024-04-20 16:59:43,491 [INFO] [business.mqtt:66] Payload partial
> 2024-04-20 16:59:43,510 [INFO] [business.mqtt:87] Security Level update ! Setting to partial
> {'status': 'partial'}
> 2024-04-20 16:59:43,866 [ERROR] [business.mqtt:209] Error when processing message: 401 Client Error: Unauthorized for url: https://api.myfox.io/v3/site/Oz2ff39iztTVL9pk9je2Fr1m8dsFWhYU/security: somfyProtect2mqtt/Oz2ff39iztTVL9pk9je2Fr1m8dsFWhYU/command => b'partial'

A restart fix the issue.

**Comment by Minims** [comment]
Hello,

est ce que plus haut dans les logs tu n'as pas une erreur lors du refresh du token que je puisse voir à quel moment je peux peut etre retenter une identification.
