### ISSUE TITLE
video streaming 2min max ?

### ISSUE THREAD

**Issue by kahatie** [Minims/SomfyProtect2MQTT#162]
hello

je n'arrive pas a garder le flux video plus de 2 min 

j'ai tester la method MQTT et go2rtc et après 2min l'image freeze 

j'ai l'impression que le script ne récupérer pas le nouveau lien du flux

**Comment by Minims** [comment]
Hello,

Oui c'est normal c'est le comportement voulu par somfy. 
On demande un lien de streaming. 
Ce lien RTMPS ne peut etre lu qu'une fois et que par un seul client. Il a une durée de 120s environ.

Alors c'est valable pour la Somfy Indoor Camera. Il se peut que ce soit different avec l'outdoor camera qui n'a pas de volet.

j'avais précisé ceci dans la Doc.

```
Somfy does not provide a permanent streaming URL. This is a On-Demand stream, and the stream is live for about 120s.
```

Unique solution que je vois, faireun automatisation qui fait stream_stop / stream_start toutes les 120s ~ pour avoir le nouveau lien rtmps et poursuivre la lecture video.

Perso je n'utilise plus cette solution pour le moment. J'ai appairé la camera via homekit dans HA et je l'ai configuré en restream dans go2rtc. J'ai du coup la camera dans homekit et go2rtc. Ca marchotte. Je crois que que ca gere automatiquement le stream > 120s.

**Comment by kahatie** [comment]
ha ok je penser que justement c'est ce que permettais de faire go2rtc.
des que le flux ce terminer il relancer le script somy.sh pour récupéré un nouveau lien.

**Comment by Minims** [comment]
C'est le switch *_stream qui déclenche l'obtention d'une nouvelle URL. got2rtc ici permet d'avoir une camera unique avec lien dynamique.
