### ISSUE TITLE
Presence doesn't match the app info

### ISSUE THREAD

**Issue by sudomax** [Minims/SomfyProtect2MQTT#164]
Fob says at home on the app while it says away with somfy2mqtt.

**Comment by Minims** [comment]
Hello, do you speak of `device_tracker.badge_de_****_presence` entity ?

**Comment by sudomax** [comment]
I'm using the key fob

**Comment by Minims** [comment]
There is many entity for the keyfob, and at least 2 report key fob presence. 
I think it the _presence entity here, update via websocket. 
If it's this one I can't do anything as Somfy websocket is not as stable as expected to have no false positive.

**Comment by sudomax** [comment]
I'm using device_lost. I don't think presence entity was there when I first
set it up.


From your message, I understand _presence cannot be trusted either?

**Comment by Minims** [comment]
None of them can be trust.. There is no api call telling is someone is at home or not.

`_presence` is based on websocket. it usually miss some messages.
`_device_lost` is based on signal seen by the Link. 
It can be NOT SYNC if : 
 - Addon was in bad state when status has changed. An add-on  restart can fix.
 - Link has not update the status. You can try the `reboot` button in HA.

In all case you need to change next badge change to validate it works again. (it means for example if not home, wait until the badge is home again )

Sorry, I will not be able to give more accurate entities with the tools provided by somfy.

**Comment by sudomax** [comment]
Thank you for the extra info!
