### ISSUE TITLE
Impossible to disable notification sound siren

### ISSUE THREAD

**Issue by Thyphus** [Minims/SomfyProtect2MQTT#18]
I have an issue with the siren of somfy protect.
There is a switch to disable or enable sound notification.

When I disable the sound in HA, the switch come back in true state after one second. On the somfy app the notification is always activate.

When I disable on the somfy app, the switch become false after few seconds in HA. I enable the sound notification in HA and this time it works. So it's just the disable which doesn't work (It's the same thing for light notification).

In general every things works good :)

**Comment by Minims** [comment]
Hello, 

I will look a at it. 
I need to make some tests to find the issue, but I know I have not fully implemented the device configuration.

**Comment by Thyphus** [comment]
Hello,

Ok thank you.
If you need I can make test.

**Comment by Minims** [comment]
Hello, 

I have made a fix on the dev branch, it might be ok
