### ISSUE TITLE
Direct access to attributes of device

### ISSUE THREAD

**Issue by tutsisback** [Minims/SomfyProtect2MQTT#2]
Hi there ! it's me again.

I've been playing a little bit on HA this afternoon and I was wondering how did you manage to display the temperature given by a motion sensor (as it can be seen on your screenshot), on a HA dashboard ?

When I try to simply had a new card on the dashboard the only entites available for a motion sensor are :  

- xxx auto_protect_enabled
- xxx light_enabled
- xxx night_mode_enabled
- xxx prealarme_enabled

To get the same result as you (I mean, a card displaying the temperature), I had a long journey...

I dig into the entity info through MQTT integration menu to be able to know the topic providing the required information : 

It gives something like : somfyProtect2mqtt/sddqsdfqsfdfdfdfdsdsf/fdqfdfdfdsfdsfs/state

Then I switch to Node Red integration, made up a really simple flow with : mqtt_in --> function --> mqtt_out

mqtt_in is set on the topic I've found, the function isolate the temperature and mqtt_out forward the temperature on a specific topic.

Then I created a sensor (in yaml config file ) which read the topic of my mqtt_out node.

I'm pretty sure that it's not the proper way to do so...

**Comment by tutsisback** [comment]
Never mind, I can bypass Node Red by using the topic I've found directly in the sensor declaration in yaml config file.

Did you also do that ?

**Comment by Minims** [comment]
Hi,

In HA, you have MQTT integration with discovery enabled, the temperature sensor will appears on Motion Sensor Device automatically. I have not made anything in my YAML configuration of HA to display those sensors.

Data of the devices / sites are in somfyProtect2mqtt/
sddqsdfqsfdfdfdfdsdsf is the site_id
fdqfdfdfdsfdsfs is the device_id

And you will get the config for HA in homeassistant/{device_type}/{site_id}_{device.id}/{sensor_name}

I will check if I have not broke HADiscovery for temperature in my last commit.
