### ISSUE TITLE
MissingTokenError: (missing_token) Missing access token parameter.

### ISSUE THREAD

**Issue by WhistleMaster** [Minims/SomfyProtect2MQTT#22]
Hi !

Thanks for the great work ! I've tried to update to version 0.1.5 but I have the following error message:

`oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.`

Thanks for your help,
Regards,

**Comment by Minims** [comment]
Hello,

How do you use somfyProtect2MQTT ?  Standalone on a Debian ?

**Comment by WhistleMaster** [comment]
Hi !

I’m using the docker version.

**Comment by Minims** [comment]
Hum, don’t know why but it seems that this Python libre is not un to date

somfy-protect-api==0.1.8

can you rebuild the image and Check the requirements are ok ?

**Comment by WhistleMaster** [comment]
I did rebuild the image and it's working fine now, thanks !

The treynaer/somfyprotect2mqtt image does not seem to be up to date (three months old). I saw in one commit that you're pushing your own image minims/somfyprotect2mqtt, but I can't find it on DockerHub.

**Comment by WhistleMaster** [comment]
Thanks ! I've tried your image, unfortunately, it does not work, I create a new container and the log shows:

`/bin/sh: 1: [: python3: unexpected operator`

**Comment by Minims** [comment]
Will update my docker image later, thx for the feedback

**Comment by WhistleMaster** [comment]
Hi,

I've tried your latest image version, but the error is still there:

`/bin/sh: 1: [: python3: unexpected operator`

Thanks !
