### ISSUE TITLE
Question: does this needs Tahoma to work?

### ISSUE THREAD

**Issue by idefxH** [Minims/SomfyProtect2MQTT#23]
Hello, 

Just a quick question: does this work directly with the Somfy Home Alarm set, or does it require Tahoma to work?

Thanks!

**Comment by Minims** [comment]
Hello,

It works directly with the Somfy home alarm :-). Just need your username/password used in the App.
No Tahoma needed, that's was the goal.

**Comment by idefxH** [comment]
Perfect, thanks!
