### ISSUE TITLE
Error when Arming Home from HA

### ISSUE THREAD

**Issue by treynaer** [Minims/SomfyProtect2MQTT#24]
Hi,
I'm unable to arm home from HA, Arm Away is working fine.
Logs show:
`[ERROR] Error when processing message: list index out of range `

Regards,
Tim

**Comment by Minims** [comment]
Hello,

Can you try to enable debug mode on the addon and paste the new logs ?

**Comment by treynaer** [comment]
I found this via Verbose mode:

```
2022-02-21 13:08:41,590 [DEBUG] Message received on somfyProtect2mqtt/xxx/command: b'ARM_HOME'
2022-02-21 13:08:41,591 [ERROR] Error when processing message: list index out of range
```

**Comment by treynaer** [comment]
The service "Alarm control panel: Arm night" is working fine but the UI is showing an Arm Home button:

![image](https://user-images.githubusercontent.com/4507858/154964726-64fdc59c-af70-4a0f-9918-1272b9d9fa48.png)

**Comment by Minims** [comment]
I'm still working on a rework of the project, but i saw that "b'ARM_HOME'" is not normal, it must be: `armed_night`in this case. Do you use a specific alarm card ?

**Comment by treynaer** [comment]
No, it’s the default card of Lovelace. It could be a bug in HA.

**Comment by Minims** [comment]
I have made some big changes on dev branch, maybe you can test it with debug. It may deliver more logs.
