### ISSUE TITLE
Sensitivity_level as select instead of sensor type

### ISSUE THREAD

**Issue by Shkrum31** [Minims/SomfyProtect2MQTT#27]
https://github.com/Minims/SomfyProtect2MQTT/blob/9a7617ee4ba61cf89ed2da4c2d5434e7b5d6e312/somfyProtect2Mqtt/homeassistant/ha_discovery.py#L25

Any chance to set « sensitivity_level » type as « select » instead of « sensor » so that the parameter can be changed via HA ? (Similarly to « sensitivity_IntelliTag » whose type is « number »)

**Comment by Minims** [comment]
Hum, it seems used for sensitivity of PIR right ? 
Yes it possible. Need to find all the level.
Mine are at `low`

**Comment by Minims** [comment]
I have updated the dev branch with this.

**Comment by Shkrum31** [comment]
It works perfectly!
The three states from Somfy app to HA, or the other way around. Good job 👍
