### ISSUE TITLE
Presence sensor not properly updated

### ISSUE THREAD

**Issue by Shkrum31** [Minims/SomfyProtect2MQTT#28]
It looks like the presence sensor does not work properly.
Could this because of a typo problem, i.e. extra space in the following: `" payload_home"` and  `" payload_not_home"` ?
https://github.com/Minims/SomfyProtect2MQTT/blob/9a7617ee4ba61cf89ed2da4c2d5434e7b5d6e312/somfyProtect2Mqtt/homeassistant/ha_discovery.py#L57

**Comment by Minims** [comment]
Payload is working. 
I have made some tests, and home/not_home is working. 

But it seems sometimes I don't receive the message from somfy on the websocket.
Maybe an issue in my implementation.

Do you have the same behavior ?

**Comment by Minims** [comment]
I have enable retain flag for the MQTT topic of the badge. Lets see if it helps

**Comment by Minims** [comment]
> It looks like the presence sensor does not work properly. Could this because of a typo problem, i.e. extra space in the following: `" payload_home"` and `" payload_not_home"` ?
> 
> https://github.com/Minims/SomfyProtect2MQTT/blob/9a7617ee4ba61cf89ed2da4c2d5434e7b5d6e312/somfyProtect2Mqtt/homeassistant/ha_discovery.py#L57


So i have made some tests, here is my though.

I'm now using a dedicated somfy account for somfyprotect2mqtt.
I have also remove the somfy application where this account was connected.
I think disconnect is enough. 
For me it was a tablet where this app has been installed for that purpose.
Once there is no more application using the account used in HA, it seems I don't miss any web socket message.
Testing since 2 days, I didn't miss any message.

**Comment by Shkrum31** [comment]
Thanks for your feedback. I also manage your add-on through a dedicated user within Somfy 👍 it is a lot better for troubleshooting!

I had a deeper look in the Somfy App parameters, and your addon. Correct me if I am wrong but after further testing, these are my observations:

### Presence considerations

- When a badge is detected, the user associated with it becomes present **immediately** within the Somfy app. Then, the state of the `device_tracker` associated with the badge becomes `home` within HA. This can be easily monitored with the following messages:
```
[INFO] [somfy_protect.websocket:110] Update Key Fob Presence
[INFO] [somfy_protect.websocket:113]
{'profiles': ['owner', 'admin'], 'site_id': 'XXX', 'type': 'event', 'key': 'presence_in', 'user_id': 'XXX', 'device_id': 'XXX', 'device_type': 'fob', 'message_id': 'XXX'}
```
- When a badge is **no more** detected, the user associated with it becomes absent **after few minutes** within the Somfy app. Then, the state of the `device_tracker` associated with the badge becomes `not_home` within HA. This can be easily monitored with the following messages:
```
[INFO] [somfy_protect.websocket:110] Update Key Fob Presence
[INFO] [somfy_protect.websocket:113]
{'profiles': ['owner', 'admin'], 'site_id': 'XXX', 'type': 'event', 'key': 'presence_out', 'user_id': 'XXX', 'device_id': 'XXX', 'device_type': 'fob', 'message_id': 'XXX'}
```


### Badge assignment

- When a badge is associated with a user, the behavior is similar to what happens when a badge is detected
```
similar to first case above
```
- When a badge is **no more** associated with a user, the following message occurs (btw tagged "Unknown" which is not big deal I guess):
```
[DEBUG] [somfy_protect.websocket:95] Unknown message: 
{"profiles":["owner","admin"],"site_id":"XXX","type":"config","key":"remote_unassigned","user_id":"XXX","device_id":"XXX","message_id":"XXX"}
```

### Understanding the origin of the problem I encountered
It looks like I did not test correctly when I opened this issue due to a misunderstanding of the whole system. This is I think what happened when I though the presence detection was failed:
- The default behavior of the somfy App is to name badges depending on the user's name associated with (i.e., `Badge de Invité`). The name of the badge entities within HA are named accordingly automatically during the addon and mqtt initialization (i.e., `device_tracker.badge_de_invite_*`, etc...)
- When I tested the presence feature, I assigned the badge to different users. While the badge name changed within Somfy (i.e., `Badge de HomeAssistant`), the entities names within HA did not change. However, as long as the badge is associated with a user within Somfy App, their states continue to change correctly within HA. 

As a result, I was looking for a `device_tracker.badge_de_homeassistant_*` entity....
Moreover, when I unassigned the badge from any user, and then remove battery to make it disappear, its device_tracker still indicated `home` within HA! Which is normal according to my observation above (the entities are updated only when a user presence change, and therefore as long as a badge is associated with a user within Somfy App).

### To go further
I have several suggestions:
- Explain in the documentation that the entities created for badges within HA are linked to the device itself, and not the user associated with (contrary to what one think when using the Somfy App). The name of the entities can be changed within HA without any problem (for example, as I own only one badge, I simply renamed all entities `*.badge_*`)
- After a "presence_out" or a "remote_unassigned" event, it could be interesting to make entities associated with badges as `unavailable` or `unknown`

**Comment by Minims** [comment]
Managed in release 0.1.7
It seems we miss some message about tag presence from somfy. 
I can't fix this.
I might use a BLE integration in addition with an ESP32 to check tag presence.
