### ISSUE TITLE
How start camera  ?

### ISSUE THREAD

**Issue by Tonylolo** [Minims/SomfyProtect2MQTT#38]
Hi,

I don't find how start my camera, what entity I must use to do that ?

If I set ON with official app Somfy on my smartphone, all is OK, it work fine.

But just how I can set ON camera with your integration HA ?

Thank you.

**Comment by Minims** [comment]
Hello,

You mean you want to open the shutter on the indoor camera ?

**Comment by Tonylolo** [comment]
Both

Open shutter for indoor and set available outdoor to obtain the live.

**Comment by Minims** [comment]
On my setup I use the entity `switch.indoor_camera_shutter_state` to open/close the shutter on indoor camera.
I don't know how it work with the outdoor one, I have never had one.

**Comment by Tonylolo** [comment]
Yes it's same, great thank you.

Do you know if we can have the live from camera?

**Comment by Minims** [comment]
Right now no.
I can have the somfy url to get WebRTC stream from the android App code, but I don't know how it works.
I need someone to know how to work with WebRTC stream.

**Comment by Tonylolo** [comment]
Ok i hope that someone will help you on this subject.
After it'll be perfect
Thk you

**Comment by Tonylolo** [comment]
Hi
About shutter state, i don't understand but it isn't work at each time...is there another settings to set?
Thank you

**Comment by Minims** [comment]
Hello, can you describe

**Comment by Tonylolo** [comment]
Hi
Since i have problem i ´ll do.
