### ISSUE TITLE
No discovery in HA

### ISSUE THREAD

**Issue by hcrohland** [Minims/SomfyProtect2MQTT#46]
Hi,

I am running SomfyProtect2MQTT as a docker image since I am not using home assistant OS or supervisor.
It is connected both to the MQTT broker and to Somfy. 
I can see the status messages from my Sonfy One in the MQTT integration in HA. But I do not see the autodiscover messages and no devices get discovered.
Any idea?

**Comment by Minims** [comment]
Hello,

The problem is not clear for me. 
The somfy one has been discovered and is pushed in mqtt but you have some others devices and they are not discovered in HA ? 

We can switch to french if it’s better ;-).

**Comment by hcrohland** [comment]
Je n'ai qu'un Somfy One, pas d'autres appareils. 
Je peux voir les messages d'état de l'appareil sur le mqtt. 
Mais la caméra n'est pas découverte dans HA. Et je ne vois aucun message d'annonce de périphérique sur mqtt.

**Comment by Minims** [comment]
Ok, je n'ai jamais eu de Somfy One, donc ce n'est pas bien géré.
Vu ta description de profil je pense que tu n'auras aucun mal a lancer un bout de code python que je vais t'envoyer.
Si tu peux me coller le retour du script, je ferai l'integration de la SomfyOne.

**Comment by Minims** [comment]
Install ces paquets
```
sudo apt install python3 python3-pip
pip install somfy-protect-api
```

Cree le fichier debug.py avec ce contenu et remplace USERNAME/PASSWORD par tes identifiants Somfy

```
Le code python3 de debug.py

```
#!/usr/bin/env python3
"""Debug"""
import json
import os
import sys
import time

from somfy_protect_api.api.devices.category import Category
from somfy_protect_api.api.devices.outdoor_siren import OutDoorSiren
from somfy_protect_api.api.somfy_protect_api import SomfyProtectApi

USERNAME = "adress@mail.fr"
PASSWORD = "Pa$$W0rd"
CACHE_PATH = "token.json"

def get_token():
    try:
        with open(CACHE_PATH, "r") as cache:
            return json.loads(cache.read())
    except IOError:
        pass

def set_token(token) -> None:
    with open(CACHE_PATH, "w") as cache:
        cache.write(json.dumps(token))

if __name__ == "__main__":

    api = SomfyProtectApi(username=USERNAME, password=PASSWORD, token=get_token(), token_updater=set_token)

    if not os.path.isfile(CACHE_PATH):
        set_token(api.request_token())

    sites = api.get_sites()
    response = api.get(f"/v3/site/{sites[0].id}/device")
    print(json.dumps(response.json(),  indent=4, sort_keys=True))
```

Lance le via : 
```
pyhton3 debug.py
```

Avec les infos retournées, je pourrais ajouter la SomfyOne.
Tu peux nettoyer les valeurs de site_id / device_id dans le retour par sécurité.

**Comment by hcrohland** [comment]
Voici le résultat :

[Somfy.json.zip](https://github.com/Minims/SomfyProtect2MQTT/files/8740425/Somfy.json.zip)

En fait, j'ai un Somfy One Plus, un FOB et une télécommande.

**Comment by Minims** [comment]
Est ce que tu peux tester avec la version sur la branch dev du repo et me dire si c'est OK ?

**Comment by hcrohland** [comment]
Cela n'a rien changé. Je ne vois toujours pas de messages de découverte sur le sujet mqtt homeassistant/#

**Comment by Minims** [comment]
Tu peux me coller les logs du démarrage du script ?

**Comment by hcrohland** [comment]
somfy                  | 2022-05-21 19:51:51,318 [INFO] [__main__:50] Starting SomfyProtect2Mqtt
somfy                  | 2022-05-21 19:51:51,319 [INFO] [root:43] Reading config file /config/config.yaml
somfy                  | 2022-05-21 19:51:51,329 [INFO] [root:110] Init SSO
somfy                  | 2022-05-21 19:51:51,330 [INFO] [root:94] Init MQTT
somfy                  | 2022-05-21 19:51:51,336 [INFO] [somfy_protect.sso:75] Requesting Token
somfy                  | 2022-05-21 19:51:52,003 [INFO] [root:40] Init SomfyProtect2Mqtt
somfy                  | 2022-05-21 19:51:52,320 [INFO] [somfy_protect_2_mqtt:63] Found 1 Site(s)
somfy                  | 2022-05-21 19:51:52,321 [INFO] [business:31] Looking for Sites
somfy                  | 2022-05-21 19:51:52,322 [INFO] [business:61] Looking for Devices
somfy                  | 2022-05-21 19:51:52,322 [INFO] [business:167] Update Sites Status
somfy                  | 2022-05-21 19:51:52,323 [INFO] [business:225] Update Camera Snapshot
somfy                  | 2022-05-21 19:51:52,323 [INFO] [business:193] Update Devices Status
somfy                  | 2022-05-21 19:51:52,594 [INFO] [somfy_protect.websocket:63] Websocket Connection is READY

**Comment by hcrohland** [comment]
Hé, ça marche maintenant. J'avais mélangé "sites" avec "chambres" :-(

Merci pour votre aide !

**Comment by Minims** [comment]
Top je vais merge sous peu dans master du coup. Merci pour le retour.
