### ISSUE TITLE
Wrong support type for Intellitag

### ISSUE THREAD

**Issue by hcrohland** [Minims/SomfyProtect2MQTT#48]
Dans les journaux de mon homeassistant, je trouve beaucoup de ce message :

```
Logger: homeassistant.components.mqtt.select
[...]
First occurred: 22. Mai 2022, 20:46:35 (628 occurrences)
Last logged: 07:41:16
Invalid option for select.tur_support_type: 'garage' (valid options: ['slidedoor', 'window', 'externdoor', 'slidewindow'])
```

Ils semblent être générés par ce message mqtt :

`somfyProtect2mqtt/***/***/state {"recalibration_required": "False", "recalibrateable": "False", "cover_present": "False", "battery_level": "100", "rlink_state": "0", "rlink_quality": "-68", "rlink_quality_percent": "75", "device_lost": "False", "last_status_at": "2022-05-22T18:33:03.000000Z", "sensitivity": "7", "support_type": "garage", "night_mode_enabled": "True", "prealarm_enabled": "True"}`

Le dispositif correspondant est un capteur de porte Intellitag.

**Comment by Minims** [comment]
Je viens de corriger en dev a l'instant
