### ISSUE TITLE
Unable to run it on RaspberryPi3

### ISSUE THREAD

**Issue by FabienG42** [Minims/SomfyProtect2MQTT#5]
Hello,
Thank you for sharing this project here.
I also have this somfy alarm, so I am very interrested to integrate it into Home assistant :)
I was able to copy your depot but the custom component refuse to start on mi RPI3.
I have the following error on my supervisor terminal : 

`21-04-15 08:28:54 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-04-15 08:29:02 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with c53cd0b5_somfy-protect-2-mqtt!
21-04-15 08:29:02 ERROR (SyncWorker_3) [supervisor.docker] Image c53cd0b5/aarch64-addon-somfy-protect-2-mqtt not exists for addon_c53cd0b5_somfy-protect-2-mqtt
21-04-15 08:29:02 ERROR (MainThread) [supervisor.misc.tasks] c53cd0b5_somfy-protect-2-mqtt watchdog reanimation failed with `

I have no idea wath it means ...

**Comment by Minims** [comment]
Hello,

How did you setup the add-ons ?
Which add-on repo have you used ? The problem is on add-on installation ? 
Have you are using HA OS, HA Supervisor, Custom install  ?

**Comment by FabienG42** [comment]
Hello Mimins ,
Thank you for you answer.
Just reinstall every thing and ...  it works great now ! (I don't have any idea why but i think my connection was instable during fisrt install) 
This is  amazing job congratulation and thank you very much :)
