### ISSUE TITLE
Broken since update

### ISSUE THREAD

**Issue by rpartapsing** [Minims/SomfyProtect2MQTT#52]
Hi,

Since the new version It's broken for me with this error message:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sso.myfox.io', port=443): Max retries exceeded with url: /oauth/oauth/v2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff76ee2fb50>: Failed to establish a new connection: [Errno 13] Permission denied'))
```

My mqtt config:
```
host: 192.168.178.xxx <- local ip of HA
port: '1883'
ssl: false
username: mqtt-user
password: <pw>
client-id: somfy-protect
topic_prefix: somfyProtect2mqtt
ha_discover_prefix: homeassistant
```

What could be the issue? Previously it worked fine. (< v0.2.0). Now I am on v0.2.1.

**Comment by Minims** [comment]
Hello,

This is quite strange.
0.2.0 is OK ?
0.2.1 is KO ?

How do you use somfyProtect2MQTT ? 
- Docker image (from docker hub, a personal one ?)
- run directly via python3 on a server
- HASSIO addon ? 

Does a rollback to 0.2.0 fix the issue ?

**Comment by rpartapsing** [comment]
Hi @Minims , thanks for your quick reply.
0.2.0 does not work, and 0.1.10-deprecated neither.
I am using the HASSIO addon and running mosquitto broker add on
Other config:
```
username: <my_mail_address>
password: <pw>   <- these creds I use to login to the somfy protect app
sites:
  - <mysitename>
code: <my_code>
code_arm_required: false
code_disarm_required: true

logs mosquitto broker:
```
1654682230: New connection from 172.30.32.2:46424 on port 1883.
1654682230: Client <unknown> closed its connection.
```

also tried 172.30.32.2 as a host but no luck.

> Hello,
> 
> This is quite strange. 0.2.0 is OK ? 0.2.1 is KO ?
> 
> How do you use somfyProtect2MQTT ?
> 
> * Docker image (from docker hub, a personal one ?)
> * run directly via python3 on a server
> * HASSIO addon ?
> 
> Does a rollback to 0.2.0 fix the issue ?

**Comment by Minims** [comment]
Can you enable debug in config and paste the full log. Remove your token before. Paste the config without login / password too.
I think the issue is in the config file.

**Comment by rpartapsing** [comment]
debug was flagged already. here is the full log (no debug messages unfortunately

```
s6-rc: info: service legacy-services successfully started
[01:42:16] INFO: Generating config.yaml from options.json
[01:42:16] INFO: Configuration :
[01:42:16] INFO: # Generated by homeassistant, do not edit!
# Edit configuration only at the Add-on configuration tab!
debug: true
delay_device: 60
delay_site: 10
homeassistant_config:
  code: xxx
  code_arm_required: false
  code_disarm_required: true
manual_snapshot: true
mqtt:
  client-id: somfy-protect
  ha_discover_prefix: homeassistant
  host: 172.30.32.2
  password: xxxx
  port: 1883
  ssl: false
  topic_prefix: somfyProtect2mqtt
  username: mqtt-user
somfy_protect:
  password: xxxx
  sites:
    - yyyyy
  username: zzzz@gmail.com
curl: (7) Couldn't connect to server
[01:42:16] ERROR: Something went wrong contacting the API
[01:42:16] INFO: Image build
[01:42:16] INFO: starting original stuff...
2022-06-10 01:42:16,439 [INFO] [__main__:55] Starting SomfyProtect2Mqtt 0.2.1
2022-06-10 01:42:16,439 [INFO] [root:43] Reading config file /usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/config/config.yaml
2022-06-10 01:42:16,442 [INFO] [root:114] Init SSO
2022-06-10 01:42:16,442 [INFO] [somfy_protect.sso:79] Requesting Token
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
PermissionError: [Errno 13] Permission denied
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f49487a0b50>: Failed to establish a new connection: [Errno 13] Permission denied
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sso.myfox.io', port=443): Max retries exceeded with url: /oauth/oauth/v2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49487a0b50>: Failed to establish a new connection: [Errno 13] Permission denied'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/main.py", line 59, in <module>
    SSO = init_sso(config=CONFIG)
  File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect/sso/__init__.py", line 122, in init_sso
    token = sso.request_token()
  File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect/sso/__init__.py", line 80, in request_token
    return self._oauth.fetch_token(
  File "/usr/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 341, in fetch_token
    r = self.request(
  File "/usr/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 521, in request
    return super(OAuth2Session, self).request(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sso.myfox.io', port=443): Max retries exceeded with url: /oauth/oauth/v2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49487a0b50>: Failed to establish a new connection: [Errno 13] Permission denied'))
[23:42:16] WARNING: Halt add-on
s6-rc: info: service legacy-services: stopping
[23:42:16] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by Minims** [comment]
It's like a firewall issue, do you have some specific rules on iptables / apparmor ?

**Comment by rpartapsing** [comment]
seems odd since I havent touched any firewall nor iptable settings:

```
sudo iptables --list

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (5 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.30.32.6          tcp dpt:http
ACCEPT     tcp  --  anywhere             172.30.33.3          tcp dpt:9099
ACCEPT     tcp  --  anywhere             172.30.33.7          tcp dpt:8554
ACCEPT     tcp  --  anywhere             172.30.33.7          tcp dpt:1935
ACCEPT     tcp  --  anywhere             172.30.33.9          tcp dpt:3000
ACCEPT     tcp  --  anywhere             172.30.33.0          tcp dpt:8884
ACCEPT     tcp  --  anywhere             172.30.33.0          tcp dpt:8883
ACCEPT     tcp  --  anywhere             172.30.33.0          tcp dpt:1884
ACCEPT     tcp  --  anywhere             172.30.33.0          tcp dpt:1883

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (5 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere
```

tried now also 172.30.33.0    with port 1883 in SomfyProtect2MQTT conf, no luck.

**Comment by rpartapsing** [comment]
If I listen with my mosquitto broker to # (all messages) I do see messages appearing like
```
Message 222 received on somfyProtect2mqtt/9fCbJu7dsXQFnjmKKjNqF4PNJywgRiNJ/42rbGnQFRJGTYbxBa2LNmexu9IYQnFIQ/device.status at 12:10 AM:

{
    "profiles": [
        "admin",
        "owner",
        "installer_write"
    ],
    "site_id": "9fCbJu7dsXQFnjmKKjNqF4PNJywgRiNJ",
    "type": "testing",
    "key": "device.status",
    "device_id": "42rbGnQFRJGTYbxBa2LNmexu9IYQnFIQ",
    "device_lost": false,
    "rlink_quality": -74,
    "rlink_quality_percent": 75,
    "battery_level": 100,
    "last_status_at": "2022-06-01T15:24:12.000000Z",
    "diagnosis": {
        "is_everything_ok": true,
        "problems": []
    },
    "message_id": "9fCbJu7dsXQFnjmKKjNqF4PNJywgRiNJ6297849c7bb07"
}
```

So messages are appearing.
If I look at the mosquitto broker logs I see like:

```
1654890568: Client <unknown> closed its connection.
1654890688: New connection from 172.30.32.2:50264 on port 1883.
1654890688: Client <unknown> closed its connection.
1654890808: New connection from 172.30.32.2:50266 on port 1883.
1654890808: Client <unknown> closed its connection.
1654890928: New connection from 172.30.32.2:50268 on port 1883.
1654890928: Client <unknown> closed its connection.
1654891025: Saving in-memory database to /data//mosquitto.db.
1654891048: New connection from 172.30.32.2:50270 on port 1883.
1654891048: Client <unknown> closed its connection.
1654891168: New connection from 172.30.32.2:50274 on port 1883.
1654891168: Client <unknown> closed its connection.
1654891288: New connection from 172.30.32.2:50276 on port 1883.
1654891288: Client <unknown> closed its connection.
1654891408: New connection from 172.30.32.2:50278 on port 1883.
1654891408: Client <unknown> closed its connection.
1654891528: New connection from 172.30.32.2:50280 on port 1883.
```

So I dont think its a firewall thing. I would not expect an error in the SomfyProtect2MQTT using host 172.30.32.2 and port 1883 in the config and yet it does say it cant connect to server because permission denied.
I really believe the error is in the SomfyProtect2MQTT HASSIO app.

**Comment by rpartapsing** [comment]
hi @Minims ,

Do you have an update already?

**Comment by Minims** [comment]
Hello,

I have no idea how to debug this. I have no similar issue. Seems related to you personal configuration.
It seems be be something in MQTT server conf I think. try to update MQTT client ID on somfyProtect or try to reinstall the whole MQTT server.

**Comment by rpartapsing** [comment]
Hi @Minims ,

So I reinstalled the whole MQTT server as you proposed but still the same error with the HA plugin.
However when I run the docker container when the same config I get it to work, but not fully function. I only get to see the current status of my SomyProtect, I cannot control it.

This is the config I use now.
So it doesnt work with the HA plugin, and only works one 1 way with the docker container.

```
somfy_protect:
  username: <my email>
  password: <pw>
  sites:
    - <sitename>
homeassistant_config:
  code: <code>
  code_arm_required: false
  code_disarm_required: false
mqtt:
  host: 192.168.xxx.xxx
  port: '1882'
  ssl: false
  username: mqtt-user
  password: mqtt-user
  client-id: somfy-protect
  topic_prefix: somfyProtect2mqtt
  ha_discover_prefix: homeassistant
delay_site: 10
delay_device: '60'
manual_snapshot: false
debug: true
```

**Comment by peluho** [comment]
> debug was flagged already. here is the full log (no debug messages unfortunately
> 
> ```
> s6-rc: info: service legacy-services successfully started
> [01:42:16] INFO: Generating config.yaml from options.json
> [01:42:16] INFO: Configuration :
> [01:42:16] INFO: # Generated by homeassistant, do not edit!
> # Edit configuration only at the Add-on configuration tab!
> debug: true
> delay_device: 60
> delay_site: 10
> homeassistant_config:
>   code: xxx
>   code_arm_required: false
>   code_disarm_required: true
> manual_snapshot: true
> mqtt:
>   client-id: somfy-protect
>   ha_discover_prefix: homeassistant
>   host: 172.30.32.2
>   password: xxxx
>   port: 1883
>   ssl: false
>   topic_prefix: somfyProtect2mqtt
>   username: mqtt-user
> somfy_protect:
>   password: xxxx
>   sites:
>     - yyyyy
>   username: zzzz@gmail.com
> curl: (7) Couldn't connect to server
> [01:42:16] ERROR: Something went wrong contacting the API
> [01:42:16] INFO: Image build
> [01:42:16] INFO: starting original stuff...
> 2022-06-10 01:42:16,439 [INFO] [__main__:55] Starting SomfyProtect2Mqtt 0.2.1
> 2022-06-10 01:42:16,439 [INFO] [root:43] Reading config file /usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/config/config.yaml
> 2022-06-10 01:42:16,442 [INFO] [root:114] Init SSO
> 2022-06-10 01:42:16,442 [INFO] [somfy_protect.sso:79] Requesting Token
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> PermissionError: [Errno 13] Permission denied
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
>     self._validate_conn(conn)
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
>     conn.connect()
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
>     conn = self._new_conn()
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f49487a0b50>: Failed to establish a new connection: [Errno 13] Permission denied
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
>     retries = retries.increment(
>   File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sso.myfox.io', port=443): Max retries exceeded with url: /oauth/oauth/v2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49487a0b50>: Failed to establish a new connection: [Errno 13] Permission denied'))
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/main.py", line 59, in <module>
>     SSO = init_sso(config=CONFIG)
>   File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect/sso/__init__.py", line 122, in init_sso
>     token = sso.request_token()
>   File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect/sso/__init__.py", line 80, in request_token
>     return self._oauth.fetch_token(
>   File "/usr/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 341, in fetch_token
>     r = self.request(
>   File "/usr/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 521, in request
>     return super(OAuth2Session, self).request(
>   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sso.myfox.io', port=443): Max retries exceeded with url: /oauth/oauth/v2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49487a0b50>: Failed to establish a new connection: [Errno 13] Permission denied'))
> [23:42:16] WARNING: Halt add-on
> s6-rc: info: service legacy-services: stopping
> [23:42:16] INFO: Service restart after closing
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> ```

I'm having the same issue, do you manage to fix it?

**Comment by rpartapsing** [comment]
@peluho I didn't manage to fix it. Next to my HA containers I open up a terminal and `sudo docker run -v $(pwd)/somfy/:/config minims/somfyprotect2mqtt` inside the somfy dir i have a file named `config.yaml` with contents:
```
debug: true
delay_device: 60
delay_site: 10
homeassistant_config:
  code: xxx
  code_arm_required: false
  code_disarm_required: true
manual_snapshot: false
mqtt:
  client-id: somfy-protect
  ha_discover_prefix: homeassistant
  host: 192.168......
  password: xxxx
  port: 1883
  ssl: false
  topic_prefix: somfyProtect2mqtt
  username: username
somfy_protect:
  password: xxxx
  sites:
    - yyyyy
  username: zzzz@gmail.com
```

**Comment by Minims** [comment]
https://github.com/Minims/SomfyProtect2MQTT/issues/127
