### ISSUE TITLE
Unable to sound the alarm

### ISSUE THREAD

**Issue by birse29** [Minims/SomfyProtect2MQTT#54]
Hello,

I can't sound the alarm using switch.<>_siren entity in Home Assistant (latest release).
In fact, when switch status is off and I try to sound the alarm manually using the mobile app, the alarm is silent.

Do you have any idea please ?

**Comment by Minims** [comment]
Hello,

Can you enable debug mode in the configuration and paste the log of the add-on when you try to activate the siren ?  Thanks.

**Comment by birse29** [comment]
Hello,

After enabling debug mode and restarting the container I tested again to generate logs but this time it has worked...

I should have tried to restart the container first.
