### ISSUE TITLE
supported_features not correct

### ISSUE THREAD

**Issue by WhistleMaster** [Minims/SomfyProtect2MQTT#55]
Hi !

Thanks for the great work on this project ! 

I'm looking at the attribute `supported_features` of the entity created by _SomfyProtect2MQTT_ and I have the value **63**.

Not sure where it's defined in your code, but according to HA [documentation](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#supported-features):

> Supported features are defined by using values in the AlarmControlPanelEntityFeature enum and are combined using the bitwise or (|) operator.

Which means that, in HA core, [const.py L26](https://github.com/home-assistant/core/blob/ff7ef7e5265c565921ee33a4b9f4ab35290d1a1c/homeassistant/components/alarm_control_panel/const.py#L26) is defining those:

```
    ARM_HOME = 1
    ARM_AWAY = 2
    ARM_NIGHT = 4
    TRIGGER = 8
    ARM_CUSTOM_BYPASS = 16
    ARM_VACATION = 32
```

So, 63 means that all the modes are supported for _Somfy Protect_. It can be tested with bitwise operator "&" in Python:

```
# python3
>>> 63 & 0b000001
1
>>> 63 & 0b000010
2
>>> 63 & 0b000100
4
>>> 63 & 0b001000
8
>>> 63 & 0b010000
16
>>> 63 & 0b100000
32
>>>
```

Which, if I'm not wrong, is not correct, as only `ARM_NIGHT` and `ARM_AWAY` are available for _Somfy Protect_. Not sure about `TRIGGER`, if this could be detected when the alarm has been triggered. 

I think that this attribute `supported_features` should be defined somewhere and should then be **6** (or **14** if `TRIGGER` can be detected).

```
# python3
>>> 6 & 0b000001
0
>>> 6 & 0b000010
2
>>> 6 & 0b000100
4
>>> 6 & 0b001000
0
>>> 6 & 0b010000
0
>>> 6 & 0b100000
0
>>>
```

Thanks !
Regards,

WM

**Comment by Minims** [comment]
Hello,

Yes the Alarm supports TRIGGER since I listen to the websocket.

About the configuration, I don't see how I can define `supported_features` in the MQTT Alarm Control Panel : 
https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/ 

Have you any idea?

**Comment by WhistleMaster** [comment]
Thanks for your reply ! 

It seems that indeed, HA `MQTT alarm_control_panel` defines all the states by [default](https://github.com/home-assistant/core/blob/92a9011953866ace16f07e06a0b17be2841f91f6/homeassistant/components/mqtt/alarm_control_panel.py#L243).

I had a look at [Alarmo](https://github.com/nielsfaber/alarmo) integration for Home Assistant and it seems that they can define at the [alarm_control_panel level](https://github.com/nielsfaber/alarmo/blob/aec30228e34fc433ff289ac0ed47cad8c8a1426d/custom_components/alarmo/alarm_control_panel.py#L791) the [supported_features](https://github.com/nielsfaber/alarmo/blob/aec30228e34fc433ff289ac0ed47cad8c8a1426d/custom_components/alarmo/const.py#L154). 

Or maybe with the [discovery payload ](https://www.home-assistant.io/docs/mqtt/discovery/#discovery-payload) ?

`'sup_feat':            'supported_features',`

**Comment by Minims** [comment]
Hello @WhistleMaster 

I can't make it work, any idea how to set the `supported_features`.
I have tried : 
```
        "supported_features": ["arm_night", "arm_away", "trigger"],
        "supported_features": "14",
        "supported_features": 14
```

**Comment by WhistleMaster** [comment]
Hi! 

Unfortunately, I don't have any other ideas besides the one I already listed in my previous post.
