### ISSUE TITLE
Boutons armement non fonctionnels

### ISSUE THREAD

**Issue by Menama83** [Minims/SomfyProtect2MQTT#57]
## Mon problème

Bonjour Minims,

D'abord merci pour ton travail.

J'ai réussi à installer ce module, je reçois bien les modifications d'état mais lorsque je clique sur un bouton, il ne se passe rien.
![image](https://user-images.githubusercontent.com/113510898/192132621-e8e2bdfd-63ca-4fd9-ac00-5da850a33fc3.png)

Dans les log, rien
```
2022-09-23 09:57:26,745 [INFO] [business:180] Update Mon alarme Status
2022-09-23 09:57:36,757 [INFO] [business:176] Update Sites Status
2022-09-23 09:57:36,935 [INFO] [business:180] Update Mon alarme Status
2022-09-23 09:57:46,948 [INFO] [business:176] Update Sites Status
2022-09-23 09:57:47,078 [INFO] [business:180] Update Mon alarme Status
```
J'ai certainement manqué quelque chose dans la configuration.

Merci d'avance pour ton aide

## Ma configuration
___
## System Information

version | core-2022.9.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.67
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.09.1
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 30.8 GB
disk_used | 2.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | SomfyProtect2MQTT (0.2.1), File editor (5.4.1), Network UPS Tools (0.11.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 septembre 2022 à 19:37
-- | --
current_recorder_run | 23 septembre 2022 à 09:49
estimated_db_size | 1.37 MiB
database_engine | sqlite
database_version | 3.38.5

</details>
___

**Comment by Menama83** [comment]
Ca y est ça fonctionne, j'ai arrêté puis rédémarré le module et c'est bon. Par contre pas tous les boutons, j'ai modifié la carte comme ça et tout est ok pour mon besoin.
![image](https://user-images.githubusercontent.com/113510898/192146866-fa119493-1ea6-4990-8ddb-4fa6ddbbffdc.png)
Merci pour ce module super pratique

**Comment by Minims** [comment]
Hello,

J'ai fais ceci comme carte:
```
type: alarm-panel
states:
  - arm_away
  - arm_night
entity: alarm_control_panel.maison
```
