### ISSUE TITLE
Possibilité d'utiliser l'état des badges

### ISSUE THREAD

**Issue by Menama83** [Minims/SomfyProtect2MQTT#58]
Bonjour,
J'ai essayé d'avoir l'état des badges avec cette entité mais ça ne fonctionne pas pour moi. 
![image](https://user-images.githubusercontent.com/113510898/192347947-5ca4839f-cea9-4900-8778-1c3e2d3cf0c5.png)
J'ai plusieurs états différents et desvaleurs qui remontentent mais ne correspondent pas à l'appli.
Existe-t-il une autre entité ou je dois gérer la présence avec une autre intégration?
Merci d'avance

**Comment by Minims** [comment]
Hello,

J'ai le même genre de comportement.

Il semble que les états soit assez coherent s'il n'y a plus personne à la maison et si dans les réglages de vie privée de l'application, tout soit sur ON.

Mais la fiabilité des messages reçu sur le Websocket n'est pas génial pour capter les Badges.

Perso j'ai ajouté une integration ESPHOME avec BLE Tracker pour vérifier la présence des Badge.

**Comment by Menama83** [comment]
Merci Minims, je vais partir sur une gestion locale du badge avec une intégration comme tu le préconises. Encore merci pour ton travail.

**Comment by tomav** [comment]
@Minims tu utilises https://esphome.io/components/esp32_ble_tracker.html du coup pour les badges ?
Comment trouves-tu la MAC BT d'un keyfob ?

**Comment by Minims** [comment]
J'ai configure d'abord en scanner pour trouver les Mac des devices MyFox : 
https://esphome.io/components/text_sensor/ble_scanner.html?highlight=bluetooth
