### ISSUE TITLE
Trouble with connection

### ISSUE THREAD

**Issue by Akiokun** [Minims/SomfyProtect2MQTT#62]
Have some trouble finding out, how to get this to work. I surely are making a error. 

Log:
```
raise_from_error(params.get('error'), params)
  File "/usr/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) 
[18:47:48] WARNING: Halt add-on
[18:47:48] INFO: Service restart after closing
```

My config:

```
somfy_protect:
  username: xxxxxxxxxxx
  password: xxxxxxxxxxx
  sites:
    - Maison
homeassistant_config:
  code: "0"
  code_arm_required: false
  code_disarm_required: false
mqtt:
  host: 192.xxxxxxxxx
  port: "1883"
  ssl: false
  username: xxxxxxxxxx
  password: xxxxxxxxx
  client-id: somfy-protect
  topic_prefix: somfyProtect2mqtt
  ha_discover_prefix: homeassistant
delay_site: "10"
delay_device: "60"
manual_snapshot: false
debug: false
```

🤔

Best regards.

**Comment by Minims** [comment]
Hello,

Have you name your house "Maison" in the Somfy App ?  If not replace "Maison" by the correct name.

**Comment by Akiokun** [comment]
Hey, okay i found the problem, it is case sensitive,
it seams too work:
2022-10-16 15:54:30,911 [INFO] [business:176] Update Sites Status
2022-10-16 15:54:40,922 [INFO] [business:204] Update Devices Status
2022-10-16 15:54:40,922 [INFO] [business:236] Update Camera Snapshot
2022-10-16 15:54:40,922 [INFO] [business:176] Update Sites Status

but i cant see the entity or anything on the mqtt side..

**Comment by Minims** [comment]
Can you active debug mode to see mqtt logs ?

**Comment by Akiokun** [comment]
https://privatebin.net/?4dcbb5e69fdcb8e8#2LkzTpbh8HGkZsaeTNV8JpSgMc6z744bTw644naGwHaY

**Comment by Akiokun** [comment]
made some errors here....i will need to try it by myself

**Comment by Akiokun** [comment]
somfy_protect:
  username: xxxxxxxxxxx
  password: xxxxxxxxxxx
  sites:
    - Maison
homeassistant_config:
  code: "0"
  code_arm_required: false
  code_disarm_required: false
mqtt:
  host: 192.xxxxxxxxx
  port: "1883"
  ssl: false
  username: xxxxxxxxxx
  password: xxxxxxxxx
  client-id: somfy-protect  < what does this line?
  topic_prefix: somfyProtect2mqtt    < is this relevant?
  ha_discover_prefix: homeassistant <what if i change this one?
delay_site: "10"
delay_device: "60"
manual_snapshot: false
debug: false

**Comment by Minims** [comment]
> client-id: somfy-protect < what does this line?

You can define what you want here.

> topic_prefix: somfyProtect2mqtt < is this relevant?

It's the topic where MQTT message are sent. Keep it, or change it as you want.

> ha_discover_prefix: homeassistant <what if i change this one?

Needed for MQTT autodiscover. By default MQTT discover works on this topic.

> sites:
> - Maison

Are you sure you house is named Maison in you Somfy App. It seems your are in Germany, so I think the name might not be in French.

**Comment by Akiokun** [comment]
I passed the point that it doesn't started, so basically I'm now a step forward.
The problem was that I needed to write Maison - > MAISON I dont know why..
After that I get messages from somfy, but my mqtt doesn't show anything. That's why I asked you all the questions. It seams that it works on one side but not on the other.

**Comment by Akiokun** [comment]
I don't know what I did but now it works.

Thank you for the quick response and time
