### ISSUE TITLE
Can't start 0.2.4 on raspbian

### ISSUE THREAD

**Issue by ScratMan** [Minims/SomfyProtect2MQTT#66]
Hello, after updating to 0.2.4, the somProtect2Mqtt service can't start, here is the log :

```
nov. 04 07:50:18 raspberrypi systemd[1]: Started Somfy2Mqtt.
nov. 04 07:50:19 raspberrypi python3[25423]: 2022-11-04 07:50:19,151 [INFO] [__main__:55] Starting SomfyProtect2Mqtt 0.2
nov. 04 07:50:19 raspberrypi python3[25423]: 2022-11-04 07:50:19,151 [INFO] [root:43] Reading config file None
nov. 04 07:50:19 raspberrypi python3[25423]: Traceback (most recent call last):
nov. 04 07:50:19 raspberrypi python3[25423]:   File "/home/homeassistant/SomfyProtect2MQTT/somfyProtect2Mqtt/main.py", l
nov. 04 07:50:19 raspberrypi python3[25423]:     CONFIG = read_config_file(CONFIG_FILE)
nov. 04 07:50:19 raspberrypi python3[25423]:   File "/home/homeassistant/SomfyProtect2MQTT/somfyProtect2Mqtt/utils/__ini
nov. 04 07:50:19 raspberrypi python3[25423]:     if not os.path.isfile(config_file):
nov. 04 07:50:19 raspberrypi python3[25423]:   File "/usr/lib/python3.7/genericpath.py", line 30, in isfile
nov. 04 07:50:19 raspberrypi python3[25423]:     st = os.stat(path)
nov. 04 07:50:19 raspberrypi python3[25423]: TypeError: stat: path should be string, bytes, os.PathLike or integer, not
nov. 04 07:50:19 raspberrypi systemd[1]: somfyProtect2Mqtt.service: Main process exited, code=exited, status=1/FAILURE
nov. 04 07:50:19 raspberrypi systemd[1]: somfyProtect2Mqtt.service: Failed with result 'exit-code'.
nov. 04 07:50:19 raspberrypi systemd[1]: somfyProtect2Mqtt.service: Service RestartSec=100ms expired, scheduling restart
nov. 04 07:50:19 raspberrypi systemd[1]: somfyProtect2Mqtt.service: Scheduled restart job, restart counter is at 5.
nov. 04 07:50:19 raspberrypi systemd[1]: Stopped Somfy2Mqtt.
nov. 04 07:50:19 raspberrypi systemd[1]: somfyProtect2Mqtt.service: Start request repeated too quickly.
nov. 04 07:50:19 raspberrypi systemd[1]: somfyProtect2Mqtt.service: Failed with result 'exit-code'.
nov. 04 07:50:19 raspberrypi systemd[1]: Failed to start Somfy2Mqtt.
```

Can't use docker either, it fails to start with error
`python: can't open file 'main.py': [Errno 2] No such file or directory`

**Comment by ScratMan** [comment]
Latest working version is 0.1.9, so it seems the 0.1.9.2 and the change to config broke my installation (I didn't update since a while)

**Comment by ScratMan** [comment]
Managed to make the docker container work with the command : 
`docker run -v <PATH-TO-CONFIG-FOLDER>:/config minims/somfyprotect2mqtt`
Documentation should be updated.

I'll use this one instead of the service based on git repo

**Comment by Minims** [comment]
> Latest working version is 0.1.9, so it seems the 0.1.9.2 and the change to config broke my installation (I didn't update since a while)

So I think systems service needs an update.

> Managed to make the docker container work with the command : `docker run -v <PATH-TO-CONFIG-FOLDER>:/config minims/somfyprotect2mqtt` Documentation should be updated.

Feel free to make a PR :-).
I will have a look a this when I get a bit of time.

> Is the docker container minims/somfyprotect2mqtt:latest linux/arm/v7 is aligned with the dev branch ? If yes I'll use this one instead of the service based on git repo

The Docker image is based on the latest TAG, so currently is is the 0.2.4. 
I will add the tag version in the docker Image, I need to update the GitHub Action for that.
