### ISSUE TITLE
infrared motion_sensor

### ISSUE THREAD

**Issue by luca-loiacono** [Minims/SomfyProtect2MQTT#69]
Hi,
I use SomfyProtect2MQTT for my automations based on the intellitag motion_sensor.

However, I note that the motion_sensor is not detected on the volumetric sensor.

When will this feature be available?

Thanks,
Luca.

**Comment by Minims** [comment]
Hello, you mean with the PIR sensor ?

**Comment by luca-loiacono** [comment]
Yes, PIR sensor 👍

**Comment by Minims** [comment]
Somfy does not give the information on the api :-/.
Maybe there is a message on the websocket when an alarm is trigger by a PIR. 
you can test and look in mqtt if you see something. I send all websocket message to mqtt, If yes i can add it to the project.

**Comment by Minims** [comment]
@luca-loiacono have you been able to make some tests with PIR alarm Trigger ?

**Comment by Minims** [comment]
No more update, reopen if problem still exists
