### ISSUE TITLE
Alarm triggered status is not show in HA

### ISSUE THREAD

**Issue by totothekiller** [Minims/SomfyProtect2MQTT#71]
Hello,

Today, my alarm was raised (hopefully no intrusion this time) but in HA stays in 'armed_away' state.

Debug mode was off so I haven't any interesting logs.

@Minims Do you have tested this recently ?

**Comment by Minims** [comment]
Hello,

No tested recently. But if the alarm has been triggered, you must have a message in MQTT from comfy websocket.
If you have it can you paste. ?

**Comment by totothekiller** [comment]
Nothing special in the logs (I was not in debug mode) ...
I'll need to try later with debug mode.

**Comment by Minims** [comment]
Any update ? @totothekiller

**Comment by Minims** [comment]
No more update, reopen if problem still exists
