### ISSUE TITLE
Error with internal door for somfy

### ISSUE THREAD

**Issue by qlaffont** [Minims/SomfyProtect2MQTT#73]
Hello,
Thanks for your repository first !

I just want to share a new error I have with my Somfy configuration just to help future issue or not. (currently I have no error on my configuration):

```
Invalid option for select.porte_support_type: 'interndoor' (valid options: ['slidedoor', 'window', 'externdoor', 'slidewindow', 'garage'])
```

Regards
Quentin

**Comment by Minims** [comment]
Hello,

It must now Work on dev branch. I will release a bit later

**Comment by Minims** [comment]
Done : https://github.com/Minims/SomfyProtect2MQTT/releases/tag/0.2.5
