### ISSUE TITLE
Configuration configuration.yaml

### ISSUE THREAD

**Issue by flopepe74** [Minims/SomfyProtect2MQTT#76]
Bonjour, 

je viens d'installer SomfyProtect2MQTT. 

Les journaux sont ok mais je ne vois pas les entités de mes appareils somfy. 

Il y a t'il une configuration a rajouter sur le fichier configuration.yaml. 

Merci d'avance pour votre aide 

Bonne soirée

**Comment by Minims** [comment]
Hello,

1. Dans la configuration, est ce que cette partie correspond bien au nom défini dans l'application Somfy:
```
sites:
  - Maison
``` 

Tu dois avoir ceci dans les logs:
```
2023-01-07 21:59:55,371 [INFO] [root:40] Init SomfyProtect2Mqtt
2023-01-07 21:59:55,853 [INFO] [somfy_protect_2_mqtt:63] Found 1 Site(s)
2023-01-07 21:59:55,854 [INFO] [somfy_protect_2_mqtt:65] Found Site : Maison
2023-01-07 21:59:55,854 [INFO] [somfy_protect_2_mqtt:67] Storing Site ID for Maison
2023-01-07 21:59:55,856 [INFO] [business:31] Looking for Sites
```

2. Est ce que l'integration MQTT dans HA a bien été reconfigure avec l'option `discovery` ?

**Comment by Minims** [comment]
Readme updated (Requirements part)

**Comment by cancan92** [comment]
Bonsoir Minims

J'ai trouvé ton intégration qui m'a l'air top à la place d'IFTTT. J'ai tenté de configurer l'add-on mais j'ai toujours l'info qu'il trouve 0 site en retour :
<img width="634" alt="Capture d’écran 2023-01-15 à 22 02 04" src="https://user-images.githubusercontent.com/38877466/212567135-0c33d8e8-caeb-4aff-a020-3c8f30837f98.png">

En mode debug je vois bien que les échanges de jetons avec Somfy marchent pourtant.
Et il me dit mettre tout le temps à jour le status (update sites status).

J'ai fait toutes les mises à jour système d'HA mais cela ne change pas. J'ai bien vérifié que le nom du site Myfox est le même que dans ma conf (Maison). La conf MQTT semble bonne aussi (j'utilise Zigbee2mqtt).

Peux-tu m'aider où je fais erreur ?
