### ISSUE TITLE
Intellitag Motion_sensor gets triggered without motion

### ISSUE THREAD

**Issue by reschix** [Minims/SomfyProtect2MQTT#79]
Hi,

first of all I want to thank you very much for this amazing piece of code. Finally I can use my Somfy One+ incl. all my Intellitags. Since there is no way (yet) to get a home assistant event in the Somfy pre-alarm phase (which I would use for lights, shutters, etc., also helps you notice a false alarm when at home), I have been creating a custom alarm panel and using all the Motion_sensor signals in the trigger automations.

Today I had my first false (Home assistant) alarm, because the sensors keep triggering sporadically. Does that have anything to do with the last update? Do you think using the motion_sensor signal is a good way of using the intellitags?

Thanks & best regards,
Reschix

**Comment by Minims** [comment]
Hi

About prealarm: it would be interesting to run the addon in debug mode and check the logs. Maybe there is a websocket message when prealarm is triggered.

you use the motion_sensor entity of an intellitag to trigger the alarm and don’t let somfy do that ? If yes, i can confirm this will give false positive if the somfy alarm is not active

**Comment by reschix** [comment]
Unfortunately there seems to be no websocket message... the Android app itself doesn't even react on the prealarm.
Only the door moving message shows up:
`2023-01-09 23:09:41,929 [INFO] [somfy_protect.websocket:326] It Seems the Door 8gml9IJCNdJPDX8SZ7fqMgMAqRQFmvXK is moving
`

Do you think the "motion_sensor" entity would be reliable while Somfy is armed? Because then I could still keep my motion_sensor trigger automations for pre-alarm actions (--> only fire if Somfy is armed) and use the Somfy alarm panel for the rest

**Comment by Minims** [comment]
Not sure. It would need to check the websocket message received when an alarm is trigger by an intellitag. 
If there is the device id in the message I might create a new entity. I can't test this for now. but you need to be in debug mode, all web socket message are displayed, and sent to mqtt topic.

**Comment by reschix** [comment]
So this websocket message that I quoted above is not connected to the motion_sensor entity yet, correct? A separate entity would probably the most reliable way to go then. What information do you need from me for that?

**Comment by Minims** [comment]
This message is connected to the motion_sensor device for intellitag: 
```
        # {
        # "profiles":[
        #     "admin",
        #     "owner",
        #     "installer_write"
        # ],
        # "site_id":"XXX",
        # "type":"testing",
        # "key":"device.status",
        # "device_id":"XXX",
        # "device_lost":false,
        # "rlink_quality":-73,
        # "rlink_quality_percent":75,
        # "battery_level":100,
        # "recalibration_required":false,
        # "cover_present":true,
        # "last_status_at":"2022-03-16T16:06:56.000000Z",
        # "diagnosis":{
        #     "is_everything_ok":true,
        #     "problems":[
        #     ]
        # },
        # "message_id":"XXX"
        # }
```

This one for motion_sensor on PIR:

```
        # {
        # "profiles":[
        #     "owner",
        #     "admin",
        #     "custom",
        #     "family",
        #     "neighbor"
        # ],
        # "site_id":"XXX",
        # "type":"alarm",
        # "key":"alarm.trespass",
        # "device_id":"XXX",
        # "device_type":"pir",
        # "start_at":"2022-03-14T17:17:12.000000Z",
        # "start_siren_at":"2022-03-14T17:17:42.000000Z",
        # "end_at":"2022-03-14T17:20:42.000000Z",
        # "end_siren_at":"2022-03-14T17:20:42.000000Z",
        # "manual_alarm":false,
        # "message_id":"XXX"
        # }
```

**Comment by Minims** [comment]
He it would be great to check if when an alarm is trigger by an intellitag, a websocket message arrive with type/key alarm and a device_id and/ord device_type. If you can have this I would update/create the motion_sensor entity

**Comment by reschix** [comment]
The websocket message I quoted above has this 32 digit Alphanumerical sequence in it that I shortened it with xxx. Its device type is window, so I guess the "door" is a default value in this websocket message. I tried it with another sensor, same result with different xxx.

**Comment by Minims** [comment]
You mean you this to type of message in web socket ? 
```
        # "device_type":"window",

```
and
```
        # "device_type":"door",

```

If yes I will update/add  the entities

**Comment by reschix** [comment]
No, I can only see this message:
`2023-01-09 23:09:41,929 [INFO] [somfy_protect.websocket:326] It Seems the Door xxx is moving `
(xxx = 32 digit Device ID)

The thing I meant was that it always says "Door" in this message, no matter if the device_type is for example window.

**Comment by Minims** [comment]
Can you enable debug in config and check the complete websocket message when door is opened while alarm is on ?

**Comment by reschix** [comment]
I have it running. That's what I am trying to say -

**Comment by reschix** [comment]
Sorry, I didn't mean to close it.

**Comment by reschix** [comment]
@Minims any news on this yet? Do you need more information from my side?

**Comment by Minims** [comment]
```
It Seems the Door xxx is moving
```

This message is based on the testing message received on the websocket. 
I think this message arrived when `rlink_quality`change. So usually signal change while moving, but sometimes it can just change because of the environment.

For the moment I don't see what I can do to avoid false positive when alarm is `disarmed` as comfy does not give a message  when it really detects that the door is moving.
If you have any idea about what we can do, tell me.

**Comment by reschix** [comment]
I did not see this message changing other than when the system was actually armed and the alarm got triggered. I will try to verify this by getting a long piece of debug output.
