### ISSUE TITLE
Security Camera shutter control doesn't work.

### ISSUE THREAD

**Issue by ScratMan** [Minims/SomfyProtect2MQTT#80]
Hello,

I'm facing an issue with the security camera shutter state control. I have the entity switch.camera_rdc_shutter_state in HA that provides the state of the shutter in real time when set by the alarm, but I can't set it on or off from HA. Is it a status only ?
If not controllable from HA, shouldn't it be a binary sensor instead of a switch?

I would like to be able to automate the camera shutter based on the status of my vacuum robot.

**Comment by Minims** [comment]
Hello,

This is quite strange. my Somfy indoor camera work great with the `Shutter_state` switch.
Do you have any errors in the logs ? 

Do you tried to do it while alarm is ON ? I have always try with alarm OFF.

**Comment by ScratMan** [comment]
This is the error message :

2023-01-11 22:06:33,966 [INFO] [business.mqtt:116] Message received for Site ID: Bd0................Hd, Device ID: ix7............................lib, Action: shutter_open
2023-01-11 22:06:34,084 [ERROR] [business.mqtt:198] Error when processing message: 401 Client Error: Unauthorized for url: https://api.myfox.io/v3/site/Bd0............................Hd/device/ix7...................lib/action

**Comment by Minims** [comment]
Do you have the error too just after restarting the addon ?
What is the addon version ?
Did you try using a dedicated user for somfy addon, not the same as the one on you phone app ?

**Comment by ScratMan** [comment]
I found the root cause: the dedicated user I added for HA was declared as a child. After setting the user as owner, there is no error in log and the shutter is working. The shutter is moving immediately, but the switch state in HA needs around 1 minute to reflect the state change.

**Comment by Minims** [comment]
Camera status is already checked 1s after the update, maybe I can increase to 2s if it's too Quick.
I will update the Readme to specify the user to use. Thanks.

**Comment by Minims** [comment]
https://github.com/Minims/SomfyProtect2MQTT/releases/tag/0.2.7

**Comment by ScratMan** [comment]
Thanks for the new release. Switch now goes on, off and finally on again quickly, no need to wait several tens of seconds to get the real state of the switch. Thanks.
