### ISSUE TITLE
Found 0 site(s)

### ISSUE THREAD

**Issue by cancan92** [Minims/SomfyProtect2MQTT#84]
Bonsoir Minims

J'ai trouvé ton intégration qui m'a l'air top à la place d'IFTTT. J'ai tenté de configurer l'add-on mais j'ai toujours l'info qu'il trouve 0 site en retour :

<img width="634" alt="Capture d’écran 2023-01-15 à 22 02 04" src="https://user-images.githubusercontent.com/38877466/212568218-ed2296f1-41f0-404f-8ce2-561a2c93eae3.png">

En mode debug je vois bien que les échanges de jetons avec Somfy marchent pourtant.
Et il me dit mettre tout le temps à jour le status (update sites status).

J'ai fait toutes les mises à jour système d'HA mais cela ne change pas. J'ai bien vérifié que le nom du site Myfox est le même que dans ma conf (Maison). La conf MQTT semble bonne aussi (j'utilise Zigbee2mqtt).

Peux-tu m'aider à trouver où je fais erreur ? 🙏

**Comment by Minims** [comment]
Hello, 

C'est bizarre que ca trouve 0 site. Tu as quel modele d'alarme ? 
Est ce que ton user est bien indiqué en tant que propriétaire dans l'application Somfy ?

**Comment by cancan92** [comment]
La centrale Myfox HC2. Ca marche avec cette alarme ? Et mon email est bien celle du user de l'appli.

**Comment by Minims** [comment]
Elle n’est pas compatible, il faut une home alarm/advanced ou une one/one+
Ton alarme utilise une ancienne api : https://api.myfox.me/dev/documentation 
Seul l’authentification est sur la meme api.

**Comment by cancan92** [comment]
Merci pour ton retour. J'aurais eu un petit espoir ;-)
Je vais continuer avec IFTTT alors.
Beau boulot en tout cas !

**Comment by cancan92** [comment]
Besoin très similaire à ce que tu as fait avec Somfy mais a minima pour me passer d'IFTTT:
- connaître l'état de l'alarme (désactivée, activée, partielle, alarme)
- pourvoir changer le status de l'alarme depuis HA

Aucune idée du nb d'utilisateurs. Je fais parti des derniers mohicans sous Myfox ? Et je n'ai aucun talent de dév

**Comment by Minims** [comment]
Tu sais lancer un script python comme somfyProtect2mqtt sur ta machine pour debugger (sans l'addon) ?

**Comment by cancan92** [comment]
J’ai déjà passé quelques commandes depuis le terminal. Avec un peu d’aide, je devrais y arriver.

**Comment by Minims** [comment]
Sinon tu as aussi ce plugin homebridge : https://github.com/Jorire/homebridge-myfoxhc2
ensuite tu actives l'integration HomeKit et tu récupères l'alarme dans HA.

**Comment by cancan92** [comment]
Bonjour Minims,
J'ai regardé rapidement. Il me manque visiblement node.js pour pouvoir exécuter des commandes. On peut avoir confiance en ce plugin (peu utilisé) ? Visiblement  l'option --unsafe-perm peut être dangereuse (elle permet de contourner les vérifications de sécurité lors de l'installation, il est donc recommandé de ne l'utiliser qu'avec des modules connus et fiables).

**Comment by Minims** [comment]
Hello,

Je ne sais pas dire si cela est "bien", je ne pourrais pas le tester. 

J'ai regardé un peu sinon , je dois pouvoir faire une version basic pour la MyFox HC2, mais il me faut un peu de temps et il faudra tester régulièrement pour valider l'avancée.

**Comment by cancan92** [comment]
Hello,

Très sympa de ta part et vraiment up to you. Bien sûr ok pour tester si tu te lançais.

**Comment by Minims** [comment]
T'emballe pas, c'est pour valider que ca fonctionne.
Il y a un nouvel addon MyFox2MQTT dans le meme repos d'addons que somfyProtect. Il va apparaitre dans HA normalement.

Est ce que tu peux l'installer, le configurer, et créer ici une application personnelle afin d'avoir un clientID/clientSecret à mettre dans la config 
https://api.myfox.me/dev/authentication

Ensuite tu le lances, ca va planter et se relancer en boucle. Mais si tu peux me donner les logs, ca me permettra d'avancer.

**Comment by cancan92** [comment]
Merci Minims ! J'ai trouvé l'addon. Je l'installe et te dirai. Possible de t'envoyer les logs en mp ?

**Comment by Minims** [comment]
Tu peux m'envoyer ca sur ' github at minims . fr '

**Comment by cancan92** [comment]
Un grand merci Minims pour ton addon qui permet de commander mon alarme Myfox !
Avis aux amateurs.

**Comment by Minims** [comment]
Merci pour les tests @cancan92.

Je clos cette issue.
Les prochaines issues sont a créer sur ce projet :  https://github.com/Minims/MyFox2MQTT

L'addon est disponible sur le même repo que somfyProtect2MQTT : 

[![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2FMinims%2Fhomeassistant-addons)
