### ISSUE TITLE
Cannot install - HAOS 2023.1.7 - Pi3 64

### ISSUE THREAD

**Issue by Bylb** [Minims/SomfyProtect2MQTT#87]
Hi, 

I try to install the addon to HA, get the following error message : 
_The command '/bin/ash -o pipefail -c apk add --no-cache py3-pip' returned a non-zero code: 1_

This appen from both Stable and Dev addon.

**Comment by Bylb** [comment]
HA version : latest : 
Home Assistant 2023.1.7
Supervisor 2022.12.1
Operating System 9.4
Interface utilisateur : 20230110.0 - latest

**Comment by Minims** [comment]
Hum, quite strange, I have tried on PI4 64 bits ans it's OK. it must be the same image.
Try to get update on addon repositories and try again.
Settings > Addons > Store > Check Update on top right

**Comment by Bylb** [comment]
I works ! 
Strange as I registrer depot just before.
FYI, on HA site there's 2 different image for pi4 and pi3.
Thanks !
