### ISSUE TITLE
Comment installer avec portainer

### ISSUE THREAD

**Issue by manjump** [Minims/SomfyProtect2MQTT#89]
Bonjour,
Quelle la marche a suivre pour l'installer avec portainer svp?
En déployant simplement l'image:
<img width="918" alt="Capture d’écran 2023-03-02 à 21 31 53" src="https://user-images.githubusercontent.com/124378662/222545301-88eca46f-b3c4-40bc-b701-bd052da150e6.png">
J'ai le message d'erreur suivant:
<img width="600" alt="Capture d’écran 2023-03-02 à 21 34 32" src="https://user-images.githubusercontent.com/124378662/222545709-0f5e7407-d0a9-40a9-a131-3015bf07b5ce.png">
Merci pour votre aide

**Comment by Minims** [comment]
Hello,

Avec l'image docker il te faut un fichier de config local avec la conf somfy/mqtt.
https://github.com/Minims/SomfyProtect2MQTT/blob/master/somfyProtect2Mqtt/docker-compose.yml#L7

Je ne sais pas comment faire ca avec portainer

**Comment by manjump** [comment]
Merci pour ta réponse Minims. Finalement j'ai appliqué:
docker run -v <PATH-TO-CONFIG-FOLDER>:/config minims/somfyprotect2mqtt
Une fois la commande exécuté, je n'ai qu'un dossier de crée dans PATH-TO-CONFIG-FOLDER (config): mais celui ci est vide??

**Comment by Minims** [comment]
Il faut que tu mettes un fichier config.yaml dans ton dossier local : 
https://github.com/Minims/SomfyProtect2MQTT/blob/master/somfyProtect2Mqtt/config/config.yaml.example

**Comment by manjump** [comment]
Merci Minims, ca fonctionne
