### ISSUE TITLE
Siren switch not triggering

### ISSUE THREAD

**Issue by omarquet** [Minims/SomfyProtect2MQTT#9]
When i try to trig the Siren switch (to fire the alarm manually), i then have a log error: 
[ERROR] Error when processing message: local variable 'site_id' referenced before assignment
The siren is not firing.
(look like it a problem with python of declaring some variable as 'global' before setting it ?

And when i try to stop the alarm manually (direct switch off):
[ERROR] Error when processing message: 400 Client Error: Bad Request for url: https://api.myfox.io/v3/site/<mysiteID>/alarm/stop (i removed mysiteID for convenience).

I'm using stable branch v0.1.2

**Comment by Minims** [comment]
Hello,

> [ERROR] Error when processing message: local variable 'site_id' referenced before assignment

I found the error.

> [ERROR] Error when processing message: 400 Client Error: Bad Request for url: https://api.myfox.io/v3/site//alarm/stop (i removed mysiteID for convenience).

I have an idea, I have update the API repo.

I have publish the fix on the dev branch. Can you give it a try ? Thx.

**Comment by omarquet** [comment]
2021-04-27 08:27:47,485 [INFO] Start the Siren On Site ID <MYSITE>
2021-04-27 08:27:47,690 [ERROR] Error when processing message: 405 Client Error: Method Not Allowed for url: https://api.myfox.io/v3/site/<MYSITE>/panic
2021-04-27 08:27:50,233 [INFO] Update Sites Status
2021-04-27 08:28:00,551 [INFO] Update Sites Status
2021-04-27 08:28:05,597 [INFO] Stop the Siren On Site ID <MYSITE>

**Comment by Minims** [comment]
Ok, I have made a new api update. 
Can retry on dev branch. or just rebuild the dev addon in HA ?

**Comment by omarquet** [comment]
Work great now ! Thank you for this great work.
Don't hesitate if you want to test some things :)

**Comment by Minims** [comment]
Thanks for debugging ;-) 
Not everything is tested as you can see. I need the community to test and help for debugging to have a mature project.

There is one more thing about alarm triggering. Maybe you can help : https://github.com/Minims/SomfyProtect2MQTT/issues/6

I don't know the alarm status when the siren is trigger, so I might not set the right status in HA.
If you have the info of the alarm status in MQTT, it would be very useful. Thanks.

**Comment by omarquet** [comment]
Indeed, status is not updated in HA. I trig the alarm with somfy app. Wait for more than 10 sec (which is the refresh value configured for both sites and devices). And the status is still not updated.

**Comment by Minims** [comment]
Update merge in master branch
