### ISSUE TITLE
motion_sensor inconnu 

### ISSUE THREAD

**Issue by manjump** [Minims/SomfyProtect2MQTT#91]
Bonjour Minims,

A quoi correspond motion_sensor?
En effet, sur 3 intellitags, j'ai 2 inconnu et 1 désactivé ( mode alarme non activée):

<img width="321" alt="image" src="https://user-images.githubusercontent.com/124378662/227727545-911493d5-a16c-4950-9f34-4db91a274c7f.png">

En te remerciant pour ton analyse.

**Comment by manjump** [comment]
Meme remarque que Badge de mike device_lost. Si j'ai bien compris c'est lié à l'éloignement par rapport au domicile. Alors sur 2 badges, j'en ai un qui est activé et l'autre désactivé

**Comment by Minims** [comment]
Hello, C'est un sensor qui s'active en fonction du signal du device, mais ce n'est pas fiable, et j'ai des soucis avec le retry sur la connexion websocket de somfy, ca aide pas sur cette partie.

**Comment by manjump** [comment]
Donc toutes les infos concernant un capteur ou badge sont fausses.
Ce qui est étrange, c’est qu’en redémarrant le container somfy, tout était à jour. En manipulant une porte, sans avoir mis l’alarme, j’avais les états activé/désactivé dans HA. Mais le lendemain, tout était faux

**Comment by Minims** [comment]
Oui c'est le soucis avec la connexion websocket qui donne ce comportement, je n'ai pas encore trouvé de fix pour cela.

**Comment by vxav** [comment]
J'ai trouvé que le motion sensor des intellitags marche bien (`on` quand il bouge et retour sur `off`).

Par contre celui des capteurs de mouvements sont au status `unknown`.

**Comment by Minims** [comment]
@vxav somfy ne remonte pas l'info sur les motion sensors, en tout cas pas dans l'api. je pense que seul le link a l'info. Par contre si l'alarm est déclenchée par le PIR alors l'entité doit changer de status.
