### ISSUE TITLE
Problème de synchro

### ISSUE THREAD

**Issue by bckthomas** [Minims/SomfyProtect2MQTT#93]
Hello
J'ai de manière récurrente un soucis avec ce module : je n'arrive plus à activer ou désactiver l'alarme via Home Assistant. J'ai beau cliquer sur armer ou désarmer, rien ne se passe.
Le module est bien démarré, pas de problème à ce niveau.
Un reboot du module corrige le problème.

J'ai activé le mode debug mais je ne vois rien de particulier dans les logs, si besoin je peux t'envoyer les logs complet, peut être que tu verras quelque chose.
Malheureusment je ne connais pas la fréquence, je rencontre le bug ce matin (hier soir ça fonctionnait)
J'ai redémarré ce matin le module, je peux essayer de tracker la prochaine fois où ça plante pour réduire la quantité de log.

Est ce que la valeur de delay_site peut jouer ? C'était à 10 secondes, je viens de le passer à 60. Peux etre que l'api bloque après un trop grand nombre de requêtes ?

**Comment by Minims** [comment]
Hello,

Je ne rencontre pas ce soucis ces derniers temps, mais je suis sur un délai de 60s. Je pense effectivement qu'un délai inférieur à 60s peut être bloqué par Somfy car tu fais trop de requêtes.

Est ce que le soucis s'est reproduit depuis le passage a 60s ?

**Comment by bckthomas** [comment]
Pour l'instant non, mais j'ai fait pas mal de reboot d'HA ces derniers jours, je continue à surveiller !

**Comment by birse29** [comment]
Hello,

J'avais ce soucis depuis qq jours. Je suis passé à 60s et ça remarche ;)

Merci
