### ISSUE TITLE
Présence badges

### ISSUE THREAD

**Issue by Menama83** [Minims/SomfyProtect2MQTT#94]
Bonjour,

Merci @Minims pour ce programme qui facilite bien la gestion de l'absence.

J'ai HA sur VM
![image](https://user-images.githubusercontent.com/113510898/233579666-678284f7-6b57-4782-a29e-042ce3af2ed1.png)
avec
SomfyProtect2MQTT
Current version: 0.2.9

J'aimerais rajouter pour la gestion des personnes un tracker sur les badges.
Les entités device_tracker ne fonctionnent pas.
Par contre dans l'historique, j'ai remarqué que les binary sensor device lost fonctionnent mais ne sont pas des device tracker donc pas possible de rajouter dans personnes. Et leur état est inversé pour mon besoin. Lost, ça veut dire absent et il est activé quand absent.
Existe-il une solution?

Merci d'avance

**Comment by Minims** [comment]
Hello,

Je peux exposer le device_lost en device_tracker, mais l'info n'es pas fiable chez moi.
Concernant les entités device_tracker, elles sont basées sur les messages websocket de Somfy, et ce n'est pas fiable non plus... 
La personne qui a développé pour Jeedom a le même soucis que moi sur les message websocket.

Perso, je pense qu'un tracker BLE du badge est le plus fiable.

**Comment by Menama83** [comment]
Salut,
J'ai testé depuis 2 jours le device_lost, impec chez moi. A part que activé, c'est absence.
![image](https://user-images.githubusercontent.com/113510898/233782320-abfb2608-d4d2-4beb-8ba3-c270fd0f76c1.png)
Si tu peux le mettre en tracker et inversé l'état, je serai au top

**Comment by Minims** [comment]
Hello,

Je met ca de coté pour le faire dans la prochaine release, je manque un peu de temps en ce moment pour avancer sur ce projet.

**Comment by Menama83** [comment]
Bonjour Minims,
Pas de souci, rien ne presse. Je suis déjà tellement satisfait de ton intégration.

**Comment by Psykoflex2019** [comment]
> 
Bonjour, 
Quand vous dites Device_lost, c'est bien celui du badge?
le mien reste en état désactivé!
activé signifierai Badge Absent de la maison?
je trouve ca incroyable de pas pouvoir le paramétrer depuis l'appli somfy !
merci

merci

**Comment by Menama83** [comment]
Je confirme quand Device_lost désactivé ça veut dire présent (vérifiable dans l'historique). Un retour d'expérience supplémentaire serait bien.

**Comment by Minims** [comment]
@Menama83 si je remplace le binary par device-tracker avec logique inversé sur la branche de deg tu sais tester ?

**Comment by Minims** [comment]
@Menama83 c'est disponible sur la branche de dev, il faudra effacer la config des binary sensor dans mqtt manuellement

**Comment by Menama83** [comment]
@Minims Je suis vraiment un noob, comment passer en dev? Ensuite, supprimer dans mqtt ça veut dire les entités device_lost actuels?

**Comment by Minims** [comment]
Release 2023.6.0 sorti incluant ce patch.

Tu dois pouvoir supprimer les entités plus utilisé depuis home assistant.
Je tourne ur cette version depuis un moment sans soucis.

**Comment by Menama83** [comment]
Bonjour @Minims ,
Les modifications fonctionnent très bien, merci et ça correspond au suivi d'activité (untel est parti, untel est arrivé). Malheureusement, parfois badge présent mais dans l'activité, pas de untel est arrivé et inversement. J'ai remonté le sujet auprès de SOMFY.
Par contre impossible pour moi de supprimer les entités, j'ai un message, ne peut être supprimé que si l'intégration ne l'utilise plus (j'ai essayé un redémarrage, idem).

**Comment by Minims** [comment]
J'ai publié une nouvelle version qui doit faire le nettoyage automatique.

**Comment by Menama83** [comment]
Ca fonctionne, merci.
Par contre, je ne sais pas si c'est voulu mais tous les équipements avec device_lost sont passés en tracker commes les intellitag par exemple.

**Comment by Minims** [comment]
Oui, c’est la meme donnée sur l’api donc je change les 2

**Comment by Menama83** [comment]
Merci pour tout @Minims , je ferme la question.

**Comment by Menama83** [comment]
Merci pour tout @Minims , je ferme la question.

**Comment by Psykoflex2019** [comment]
Bonjour, j'ai la version NON-dev, j'ai bien fait la MAJ.
est-ce que cela devrait fonctionné aussi?
device_tracker.badge_de_moi remonte toujours Présent alors que le badge n'est pas présent.

merci

**Comment by Minims** [comment]
> Bonjour, j'ai la version NON-dev, j'ai bien fait la MAJ. est-ce que cela devrait fonctionné aussi? 

Oui 

tu regardes bien `device_tracker.badge_de_moi_device_lost` et non `device_tracker.badge_de_moi_presence` ?

**Comment by Psykoflex2019** [comment]
> 
Exacte, sur le device_lost j'ai la valeur PRESENT aprés la maj, de mémoire j'avais désactivé avant.
sur le présence , j'ai la valeur inconnu

**Comment by Psykoflex2019** [comment]
Bonjour,
Il y a t-il une configuration spéciale a réaliser pour avoir ce fonctionnement?
J'ai supprimé le badge dans somfy, puis HA, réinstallé. le badge ne change pas d'état sur le device_lost
L'attribut est GPS, est-ce normal?

merci

**Comment by Menama83** [comment]
Bonjour,
L'état se met à jour uniquement lorsque l'on entre ou sort de la maison. Ca correspond à l'état, dans activité récente, untel est parti ou untel est arrivé.
