### ISSUE TITLE
No event when the siren is triggered 

### ISSUE THREAD

**Issue by nlebreton** [Minims/SomfyProtect2MQTT#95]
Hello

Thanks for your work. That project is definitely very useful.

Few days ago, the door of the kitchen was pushed. The alarm being armed, the siren was triggered . You can see that in the message I received. In case of doubt, my neighbors confirmed that the siren was triggered 😁.

![IMG_20230429_083941](https://user-images.githubusercontent.com/33976284/235302276-0bef0283-cb6a-4a6d-ad3d-c885c897b9ec.jpg)

![IMG_20230429_083837](https://user-images.githubusercontent.com/33976284/235302299-c228736a-9fcd-420e-b0e7-a02c6f6d750e.jpg)

I have implemented a scenario when the siren is triggered. Unfortunately, as you can see in the next picture attached, HAAS received an event for the door but not for the siren. 

![IMG_20230429_084158](https://user-images.githubusercontent.com/33976284/235302398-188c59ca-562d-4ec9-9613-7a4117d4a9b9.jpg)

Do you think that this is a big ? Can you help on it?

**Comment by Minims** [comment]
Hello,

The alarm must have been triggered. I would be nice to reproduce  in debug mode, check log and payload in MQTT alarm topic to check why the alarm is not trigger in HA.

**Comment by Minims** [comment]
This issue has been stale for 30 days - it will be closed within the next 7 days if not updated

**Comment by nlebreton** [comment]
Hello,

Sorry for the time not updating that issue. My SSD crashed, and the seller took a very long time to apply the warranty...

The  siren was triggered on yesterday during 3 minutes:

![somfy 2207](https://github.com/Minims/SomfyProtect2MQTT/assets/33976284/22fd5b33-a86b-4a20-8a0b-32f2ffd8919a)

But nothing appears in the history of hass:

![HASS history 2207](https://github.com/Minims/SomfyProtect2MQTT/assets/33976284/9dbbab40-4fea-44f5-a40a-8d24ca628e82)

This morning, I switched the logs to verbose and tried to reproduce the issue.

I switched the alarm to night mode, opened a window. 

![somfy 2307](https://github.com/Minims/SomfyProtect2MQTT/assets/33976284/2bd1dde3-59a3-4136-9d02-c51bc8646279)

Surprisingly, in the history of Hass,
- The status of the alarm remains Disarmed while it should be Armed night
- We clearly can see that the siren was triggered during few seconds until I  manually disarmed the alarm
- While the siren remains off

![HASS history 2307](https://github.com/Minims/SomfyProtect2MQTT/assets/33976284/a0287e24-3294-4210-9bc3-215ae89eb84b)

I have attached the logs of hass in debug.

[home-assistant.log.gz](https://github.com/Minims/SomfyProtect2MQTT/files/12138713/home-assistant.log.gz)

**Comment by Minims** [comment]
Ok So alarm is triggered if HA has been restarted. It seems related to the websocket. Need to check how I can improve this part.

**Comment by nlebreton** [comment]
I do agree. I sometimes see the  status 'unknown' in HASS for the device 'Maison'. The status is refreshed while restarting docker-compose but both HASS and MQTT are part of it. When I will see the unknown status again, I will restart them separately, starting by MQTT, to help you to troubleshoot that issue.

**Comment by Minims** [comment]
I have made a change on dev version will check if it's better

**Comment by nlebreton** [comment]
Awesome! 

@Minims do you have a way to reproduce the issue and then to check that your update solve it or do you need me?

**Comment by nlebreton** [comment]
I thought that restarting Hass helped to receive alerts when the alarm is triggered. That actually is wrong. 

Today I had to restart Hass and realized that Maison.triggered appears systematically when Hass is restarted.

**Comment by Minims** [comment]
It seems better, can you try the DEV adding in HA and confirm it's better ?

**Comment by Minims** [comment]
Fix pushed in version 2023.8.0 , try it

**Comment by nlebreton** [comment]
I have switched to version 2023.8.0. 

Once restarted, I didn't notice anything strange. Same after having restarted mosquitto.

I then restarted hass. I then noticed that the status of the alarm switched from disarmed to unknown. I waited about 10 minutes and the status remained the same. I launched a script to arm the alarm from hass. It didn't worked as confirmed by Somfy mobile application. 

The situation returned to normal when I restarted somfy2mqtt. 

I have checked with several other versions, and this is not specific to the version 2023.8.0. It's annoying because it means that, if for any reason, hass restart unexpectedly, then everything related to Somfy will be unavailable from hass. 

It's too late to trigger the alarm, I will do that tomorrow and then update the issue accordingly.

**Comment by Minims** [comment]
This patch is only for alarm trigger. 
need to check for the ha restart issue.

**Comment by Minims** [comment]
About the ja restart issue it is because i do not retain message in mqtt. So when mqtt integration restart, the entities are unknown.  But i though ha kept the last valie in his storage, need to dig

**Comment by nlebreton** [comment]
I have created a dedicated issue (#106) related to hass restart.

**Comment by nlebreton** [comment]
I was not able to reproduce the issue anymore. 

I restarted hass with debug mode enabled, restarted SomfyProtect2MQTT, armed the alarm, open a door. As a consequence, le siren was triggered and I was able to see that in Hass history. 

As far as I am concerned, the issue can be closed. 

Based on the above scenario, please tell me if you also think that that issue can be closed.

**Comment by Minims** [comment]
I think we can close for now. Check with 2023.8.1, but the behavior must be the same
