### ISSUE TITLE
Error Integration 

### ISSUE THREAD

**Issue by thierrysoler** [Minims/SomfyProtect2MQTT#96]
Hi
When I tried to integrate with :

- Home Assistant 2023.4.6

- Supervisor 2023.04.1

- Operating System 10.1

- Interface utilisateur : 20230411.1 - latest

and : 

- HACS Version : 1.32.1

I get the error : <Integration Minims/SomfyProtect2MQTT> Repository structure for 0.2.9 is not compliant

Thank you
Best regards

Thierry

**Comment by Minims** [comment]
Hello,

I'm unable to reproduce. How can I ? 
I have testes on PI4 64bits aarch64. All seems OK.
