### ISSUE TITLE
Setup alarm level entry with HA

### ISSUE THREAD

**Issue by fr3nchalp4a** [Minims/SomfyProtect2MQTT#97]
Hello!
I have a RPi4 running full HA (ie not in docker), and I installed the integration following the docs.
Everything is working, I can see in debug mode and in MQTT explorer that the system is polling new data, HA has discovered and added all the new devices, and using the trigger button in HA, the alarm starts.
The only thing I can't find is the alarm state button. If I add a new alarm control panel in the dashboard, HA says that no alarm has been found. If I try to add a button (like a light switch), there's no entry to switch the state of the alarm.

Thanks for your great work, and it's very useful since IFTTT isn't free anymore 😂

**Comment by Minims** [comment]
Hello,

The siren with does not do what you want ? 
```
switch.<site_name>_siren
```

the alarm entity must be return a status trigger when it's triggered while alarm is ON.

Any error in logs with debug mode ?

**Comment by Minims** [comment]
Try 2023.8.0 , you must get the alarm triggered
